### ISSUE TITLE
Support RTL for all interface elements

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1579]
### Expected Behavior

When the GUI is switched into a RTL language the UI should switch direction as well as the blocks. For example, the stage should be on the left instead of the right.

### Actual Behavior

Since we use flex-box for almost everything - it switches as expected with the `dir` attribute is set to `rtl`. Known exceptions are the `add sprite`, `add backdrop`, and `add extension` buttons. We should check for any use of `position: absolute` and make it work properly in RTL mode.

### Steps to Reproduce

Eventually the direction attribute will be set by the wrapping container (e.g. www) - for now simply set `dir=rtl` on the body of the playground.

I may split these out into separate issues, but starting to note the individual components that need to handle RTL:
- [ ] Blocks - workspace and toolbox
- [ ] Category menu
- [ ] ~Libraries [sprites, etc]~ Moved to #2756
- [ ] ~Tutorials [this may be the same as other libraries]~ Moved to #2756
- [ ] ~How-to cards~ Moved to #2758
- [ ] Action menus (the position of the options is wrong and the tooltip is on the wrong side)
- [ ] Sprite info
  - [ ] margin/padding between labels/ value
  - [ ] show/hide border style (opposite rounded corners)
- [ ] Sprite delete button - fix position
- [ ] ~Modals - preview etc~ Moved to #2759
- [ ] ~menubar menus (drop down to the right instead of left)~ moved to #2757
- [Probably won't fix] - coming soon tooltip when positioned to the side

Questions: 
- backpack?

Paint editor: Tracking in https://github.com/LLK/scratch-paint/issues/574
- fill and stroke selector styles.
- color picker layout
- zoom button borders
- undo/redo button borders
- bitmap button icon padding

Sound Editor 
- [ ] Should the 'play' button point the other direction? No it needs to stay LTR
- [ ] undo/redo borders
- [ ] padding/margins around labels

**Comment by chrisgarrity** [comment]
Sadly being able to set css based on the [dir pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir) is experimental and not supported in most browsers.
