### ISSUE TITLE
Smoke Test issues from Friday 5/4/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2002]
Please make or find an issue for each bug with your name on it below.  Add a link after the bug and check it off in a comment (or mark it as fixed.)

Bugs found in Smoke Test:
(Please link to the issue and check when issue has been filed or issue fixed)

* [x] Touch paint tools don’t work iOS Safari -- console has type errors or Android Tablet @kchadha 
* [x] Undo is not working in the paint editor @fsih 
* [x] Camera wouldn’t turn off after a while (Edge Only) @BryceLTaylor #1992
* [x] Video feed is frozen when video motion extension gets loaded -- can’t repro, no errors (iPad) @kchadha 
* [x] Video freezes in modal and stage when video motion extension gets loaded and camera modal is brought up @kchadha 
* [x] Bitmap paint editor position is slightly offset from vector editor position #1944
* [x] Converting between vector and bitmap sometimes makes sprite flash on the stage, and at least once (on convert to vector) the sprite disappeared from the stage. Converting back to bitmap brought it back. (iPad?) @kchadha 
* [x] Say block causes loop to sloooooow down On Edge (also chrome+android) Is this a regression? no @BryceLTaylor #1994 
* [x] Special number keyboard pops up way above the actual number field that prompted it (iPad) @kchadha 
* [x] Cat sprite from library gets added to the stage with costume 2 selected instead of costume 1 @BryceLTaylor #1995 
* [x] In the library, small sprites are at the top of the preview @fsih 
* [x] The Broom has exploded. In the paint editor the head and the stick are separate, but not on the stage.  On Edge only. @BryceLTaylor #1997 
* [x] If you ungroup the bear, one of the paws has the outlines not grouped with the fill so it’s hard to pose. Looks like this is true in several of the sprites @carljbowman 
* [x] Say bubble doesn’t check off stage to the left (https://github.com/LLK/scratch-vm/issues/1135)
* [x] Keypress for French keyboard is not detected @chrisgarrity https://github.com/LLK/scratch-vm/issues/1116
* [x] White shapes turn black with “change color effect” blocks @paulkaplan 
* [x] Safari – custom procedure running causes some blocks to disappear from the workspace @thisandagain https://github.com/LLK/scratch-gui/issues/2026
* [x] The speech bubble for a sprite remains in place while the sprite is dragged in editor mode. In 2.0 it moves with the sprite location, fenced to the stage. @rschamp 
* [x] Performance - Safari reports power consumption warning while Scratch 3.0 is loaded @thisandagain 
* [x] Tapping a text field on a block (i.e. “say hello”) will cause the virtual keyboard to pop open for a second and then close (also Edge/surface touch) @paulkaplan 
* [x] Rotation center issue: @thisandagain  FIXED!!
    Load dragon sprite
    Move dragon to 0, 0
    Go to costumes
    Ungroup dragon
    Switch to costume b
    Switch back to costume a
    Offset in the renderer
* [ ] Saving / loading from SB3 caused all block stacks to be loaded on top of each other (0,0?) @thisandagain

**Comment by BryceLTaylor** [comment]
* [x] Camera wouldn’t turn off after a while (Edge Only) @BryceLTaylor #1992
* [x] Say block causes loop to sloooooow down On Edge (also chrome+android) Is this a regression? no @BryceLTaylor #1994 
* [x] Cat sprite from library gets added to the stage with costume 2 selected instead of costume 1 @BryceLTaylor #1995 
* [x] The Broom has exploded. In the paint editor the head and the stick are separate, but not on the stage.  On Edge only. @BryceLTaylor #1997

**Comment by chrisgarrity** [comment]
@BryceLTaylor it turned out that my bug was due to Eric's changes not landing on develop in time for the smoke test. So the issue is already closed.

**Comment by kchadha** [comment]
* [x] Video feed is frozen when video motion extension gets loaded -- can’t repro, no errors (iPad) @kchadha LLK/scratch-gui#2006
* [x] Video freezes in modal and stage when video motion extension gets loaded and camera modal is brought up @kchadha LLK/scratch-gui#2006
* [x] Converting between vector and bitmap sometimes makes sprite flash on the stage, and at least once (on convert to vector) the sprite disappeared from the stage. Converting back to bitmap brought it back. (iPad?) @kchadha LLK/scratch-gui#2007
* [x] Special number keyboard pops up way above the actual number field that prompted it (iPad) @kchadha LLK/scratch-blocks#1506

**Comment by BryceLTaylor** [comment]
* [X] The speech bubble for a sprite remains in place while the sprite is dragged in editor mode. In 2.0 it moves with the sprite location, fenced to the stage. @rschamp https://github.com/LLK/scratch-gui/issues/1977
