### ISSUE TITLE
Smoke Test issues from Friday 5/11/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2039]
Please make or find an issue for each bug with your name on it below. Add a link after the bug and check it off in a comment (or mark it as fixed.)

Bugs found in Smoke Test:
(Please link to the issue and check when issue has been filed or issue fixed)

* [x] Slider monitors that do not overlap in 2.0 overlap in 3.0.  https://llk.github.io/scratch-gui/develop/compatibility-testing.html#10057011 @chrisgarrity (https://github.com/LLK/scratch-gui/issues/2056)
* [x] Make issues for unimplemented features: slider range editing (https://github.com/LLK/scratch-gui/issues/2053), slider decimal inputs (https://github.com/LLK/scratch-gui/issues/2052), list import from csv (https://github.com/LLK/scratch-gui/issues/2054) @paulkaplan 
* [x] Android tablet soft keypad covers the text field for opening a 2.0 project in landscape @BryceLTaylor
* [x] Fonts from #220724734 load correctly in the paint editor, but are cropped in the stage (https://github.com/LLK/scratch-paint/issues/434) @fsih 
* [x] Ungrouping the fonts from #220724734 cause their representation in the stage to change size (https://github.com/LLK/scratch-paint/issues/436) @fsih 
* [x] Monitors z-indexing feels a bit off. Unlike 2.0, the last monitor dragged does not retain the top most z-index. @carljbowman - https://github.com/LLK/scratch-gui/issues/2065
* [x] Tapping a monitor slows down the project https://scratch.mit.edu/projects/158612694/ @BryceLTaylor
* [x] List monitor has 2 scrollbars. One scroll bar does not work and one scroll bar does. The one that does work is hidden at first and can only be accessed by scrolling right. @carljbowman 
* [x] Get error page working for older iOS versions (blue one in the cabinet) (https://github.com/LLK/scratch-svg-renderer/issues/20) @paulkaplan 
* [x] Portrait on android looks awful @BryceLTaylor
* [x] List monitor draws off the edge of the screen https://scratch.mit.edu/projects/159408394/ @BryceLTaylor
* [x] Can’t scroll all the way to the bottom of a list monitor, but can scroll some @BryceLTaylor
* [x] Edge: loading the editor on Edge with multiple tabs open then pulling the editor tab out => Edge window becomes black. ~50% repro rate on my laptop. @cwillisf 
* [x] Costumes get imported grouped (things that weren’t grouped in 2.0) (#2071) @kchadha 
* [x] Entering text in landscape leaves much to be desired @BryceLTaylor
* [x] Tooltips on “Welcome to Scratch 3.0 Preview” modal’s buttons are wrong: “Not Now” has no tooltip, and the others’ tooltips appear to be internal identifiers. @cwillisf 
* [x] New sprites upload at (0,0) in 2.0, it seems to import at place near center... (#2072) @kchadha 
* [ ] After importing sprite2 file with a “mode” variable @paulkaplan 
![image3](https://user-images.githubusercontent.com/1088291/39938039-9a1526da-551f-11e8-94c9-16ee30603d6c.png)
* [x] New font baselines are super off. Here is a good project to demonstrate the misalignment: scratch.mit.edu/projects/11548531 @carljbowman  - https://github.com/LLK/scratch-paint/issues/442
* [x] Icons in the Add Menu jump to the right when you click on them @carljbowman  - https://github.com/LLK/scratch-gui/issues/2066
* [ ] Scratch 3.0 pulls whiskers off kittens :(
Project 146070174 @cwillisf 
* [x] Changing a variable with a slider monitor from 0 to “hello” moves the slider to the middle (#2073) @kchadha 
* [x] Say bubbles have a different font. Wat. @paulkaplan (fixed)
![image4](https://user-images.githubusercontent.com/1088291/39938112-d46c5010-551f-11e8-8713-7a34e2487662.png)
* [x] (Not a bug?) Checking for “key {myVar} pressed” when “myVar” is set to “á” (without quotes) does not detect “a” or “á” -- but the “á” is created by pressing AltGr+a, so maybe this is because we don’t process combos? @cwillisf 

The browser combinations we used were:

Device | Browser | Name
-- | -- | --
Windows | Chrome | Paul
Mac | Chrome | Karishma
iPad | Safari |  
Chromebook | Chrome | Andrew
Windows | Firefox | Carl
Android Tablet | Chrome | Bryce
Windows | Edge | CWF
Mac | Safari | ChrisG
Mac | Firefox | Eric R

**Comment by kchadha** [comment]
* [x] Costumes get imported grouped (things that weren’t grouped in 2.0) (#2071) @kchadha 
* [x] New sprites upload at (0,0) in 2.0, it seems to import at place near center... (#2072) @kchadha 
* [x] Changing a variable with a slider monitor from 0 to “hello” moves the slider to the middle (#2073) @kchadha

**Comment by BryceLTaylor** [comment]
@cwillisf It looks to me that Scratch 2.0 is pulling whiskers off kittens and the project creator was compensating for a bug by moving the clone to the right by 120.  Then Scratch 3.0 is drawing it in the right place.

**Comment by BryceLTaylor** [comment]
@paulkaplan I'm unable to reproduce the issue with variables in uploaded sprite2 files.  Were you using Chrome on Windows?

**Comment by kchadha** [comment]
@BryceLTaylor I think the issue you're talking about ('mode' variable via sprite upload rendering strangely) was found by @thisandagain...

**Comment by cwillisf** [comment]
[x] Edge: loading the editor on Edge with multiple tabs open then pulling the editor tab out => Edge window becomes black. ~50% repro rate on my laptop. (#2086) @cwillisf
[x] Tooltips on “Welcome to Scratch 3.0 Preview” modal’s buttons are wrong: “Not Now” has no tooltip, and the others’ tooltips appear to be internal identifiers. (#2087) @cwillisf
[x] Scratch 3.0 pulls whiskers off kittens :(
Project 146070174 (LLK/scratch-svg-renderer#23) @cwillisf
