### ISSUE TITLE
Smoke Test issue from Friday 5/18/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2097]
Please make or find an issue for each bug with your name on it below. Add a link after the bug and check it off in a comment (or mark it as fixed.)

Bugs found in Smoke Test:
(Please link to the issue and check when issue has been filed or issue fixed)

(Note:  The issues with the text tool are in another issue: https://github.com/LLK/scratch-paint/issues/454)

* [x] Transition from paint editor to blocks tab, then create a custom block, variable or list. No block shows up in the toolbox. Also renaming variables, It will appear if you switch sprites. @rschamp https://github.com/LLK/scratch-gui/issues/2120
* [x] Make a block modal -- make icons in add input/label buttons non-draggable @kchadha #2126
* [x] Double-clicking a monitor while in full screen mode should not switch its state @ericrosenbaum 
* [x] Monitor double click/long press does not work well on iPad @kchadha (Filed https://github.com/LLK/scratch-gui/issues/2037)
* [x] Monitors in fullscreen go slightly off edge of stage/cover stage border @BryceLTaylor
![monitorsoffedge](https://user-images.githubusercontent.com/1088291/40249846-47035100-5aa2-11e8-868e-98ff765ddc33.png)
* [x] On a list monitor with a lot of items, I can scroll, but I cannot drag the scrollbar to scroll @ercrosenbaum (fixed in https://github.com/LLK/scratch-gui/pull/2102)
* [x] List monitor add/resize icons are hard to use on iPad @kchadha (Filed https://github.com/LLK/scratch-gui/issues/2037)
* [x] Selected list monitor slots focus area does not cover full width of slot if the list monitor is wide @kchadha 
![image10](https://user-images.githubusercontent.com/1088291/40249908-895671cc-5aa2-11e8-9075-07fc872adf1b.png) (fixed in https://github.com/LLK/scratch-gui/pull/2102)
* [x] Two x’s on a line in the list monitor @BryceLTaylor
![2xs](https://user-images.githubusercontent.com/1088291/40250173-77e0f1a0-5aa3-11e8-93db-61315c4ad9bc.png)
* [x] Slider monitor background vanishes up when you slide the slider (Safari) @rschamp As seen on Master
![image12](https://user-images.githubusercontent.com/1088291/40250192-8b429a32-5aa3-11e8-96b4-9211b6eaf131.png) (fixed in https://github.com/LLK/scratch-gui/pull/2102)
* [x] Can scroll horizontally the list monitor so the numbers disappear @BryceLTaylor (fixed in https://github.com/LLK/scratch-gui/pull/2102)
* [x] Editable text area of list monitor isn’t the whole width @BryceLTaylor (fixed in https://github.com/LLK/scratch-gui/pull/2102)
* [x] On Chrome OS, when I drag a list monitor, a little gray square appears in the upper left corner @ericrosenbaum (https://github.com/LLK/scratch-gui/issues/2110)
* [x] Crazy dancing letters when highlighting text in list monitor (from KO) Chrome mac @BryceLTaylor
* [x] Using slider on slider monitor can scroll entire page (iPad) @kchadha 
* [x] Attempting to draw with the pen using a costume that is “empty” results in the pen only drawing the bottom right quadrant of the stage. @thisandagain 
* [X] List monitor moves position. In the editor (first) it’s positioned close to the edge, in full screen it touches: @chrisgarrity https://github.com/LLK/scratch-gui/issues/2105
![image9](https://user-images.githubusercontent.com/1088291/40250334-f7b44710-5aa3-11e8-910d-c4bf1d417880.png)
![image14](https://user-images.githubusercontent.com/1088291/40250340-fa3e90da-5aa3-11e8-88d5-9fcb233b61df.png)

Device | Browser | Name
-- | -- | --
Windows* | Chrome |  
Mac | Chrome | Andrew, KO
iPad | Safari | Karishma
Chromebook | Chrome | Eric
Windows* | Firefox |  
Android Tablet | Chrome |  
Windows* | Edge | Bryce
Mac | Safari | Ray
Mac | Firefox | Carl

**Comment by BryceLTaylor** [comment]
* [X] Monitors in fullscreen go slightly off edge of stage/cover stage border @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2105
* [X] Two x’s on a line in the list monitor @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2106
* [X] Can scroll horizontally the list monitor so the numbers disappear @BryceLTaylor - fixed https://github.com/LLK/scratch-gui/pull/2102
* [X] Editable text area of list monitor isn’t the whole width @BryceLTaylor - fixed https://github.com/LLK/scratch-gui/pull/2102

**Comment by BryceLTaylor** [comment]
I think we found the same one.  I already wrote it up so I attached it to the one you found.
* [X] List monitor moves position. In the editor (first) it’s positioned close to the edge, in full screen it touches: @chrisgarrity https://github.com/LLK/scratch-gui/issues/2105

**Comment by BryceLTaylor** [comment]
* [ ] Crazy dancing letters when highlighting text in list monitor (from KO) Chrome mac @BryceLTaylor - Unable to reproduce

**Comment by BryceLTaylor** [comment]
* [X] Transition from paint editor to blocks tab, then create a custom block, variable or list. No block shows up in the toolbox. Also renaming variables, It will appear if you switch sprites. @rschamp https://github.com/LLK/scratch-gui/issues/2120

Thanks @paulkaplan

**Comment by kchadha** [comment]
@BryceLTaylor I think I'm going to leave this un-filed since I can't repro it and I'm not sure what I was referring to. We have a general issue for monitors on touch devices...

**Comment by BryceLTaylor** [comment]
Attempting to draw with the pen using a costume that is “empty” results in the pen only drawing the bottom right quadrant of the stage. @thisandagain

![penonemptysprite](https://user-images.githubusercontent.com/1088291/40435519-cdcd4508-5e7e-11e8-8bd4-df063c706f23.gif)

I'm not seeing this on chrome on mac.  Were there other conditions you were under?  I may be misunderstanding the issue.
