### ISSUE TITLE
Smoke Test issues from Friday 5/25/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2161]
* [x] Cards appear below monitors @kchadha #2189
* [x] Odd font on the last panel of cards @ericrosenbaum https://github.com/LLK/scratch-gui/issues/1961
* [x] Cards can be moved beyond page width, causing scrollbar to appear (Windows Chrome) @kchadha #2190
* [x] Cat has jagged edges in fullscreen, windows chrome (display resolution issue?) @kchadha #2208
* [X] How to is off he edge of the screen https://github.com/LLK/scratch-gui/issues/2154 @fsih 
* [x] ‘Other things to Try’ card shouldn’t include the one you’re doing - switch costumes @chrisgarrity (https://github.com/LLK/scratch-gui/issues/2176)
* [x] Card titles and ‘See more’ button in ‘More things to try!’ page of card has a serif font (Windows Chrome) different from how it renders in Mac Chrome @kchadha #1961
* [x] Make Music video has section where black bars appear in video briefly @BryceLTaylor
* [X] Card progress dots show up at different widths (selected vs. unselected) - Windows Chrome @kchadha - see note below
* [X] Should we be redirecting to youtube? https://github.com/LLK/scratch-gui/issues/2155 @fsih 
* [x] Clicking away from selected list monitor slot in the stage does not de-select monitor slot @kchadha #2207
* [X] X in list monitors is not vertically centered https://github.com/LLK/scratch-gui/issues/2156 @fsih 
* [X] Old value of list monitor flashes in when changing the value https://github.com/LLK/scratch-gui/issues/2157 @fsih 
* [X] ‘+’ in monitor list is very small https://github.com/LLK/scratch-gui/issues/2158 @fsih 
* [x] Sprites can be clicked through monitors (https://github.com/LLK/scratch-gui/issues/1998) @fsih 
* [x] If the project is listening for typing letters, typing into list monitor values can trigger those behaviors (https://github.com/LLK/scratch-gui/issues/2212) @fsih 
* [x] In scratch 2, if you click on the title of a list monitor and then press space, nothing happens, but if you click on the empty space below a list monitor and press space, then it deletes the entries. In scratch 3, if you click on the space below the list entries and press space, nothing happens, but if you click the title of the list monitor and then press space, it deletes the entries. (https://github.com/LLK/scratch-gui/issues/2213) @fsih 
* [x] Cannot select individual letters, place the cursor on iOS Safari @paulkaplan https://github.com/LLK/scratch-paint/issues/487
* [x] Text with outline looks very different in editor vs stage: @chrisgarrity https://github.com/LLK/scratch-paint/issues/480
![image4](https://user-images.githubusercontent.com/1088291/40558890-c7c822fe-6022-11e8-92f0-079abafda6a2.png)
* [X] Font looks fatter on stage than paint editor, also the same letter looks different when written  twice 
(Handwriting font) @kchadha - see note below
* [x] Text cursor goes out of the paint editor if you type a long line of text Text cursor displays out of the paint editor if you create a text block near the top of the paint editor canvas @kchadha - see note below
* [X] Sprite list doesn’t scroll in Firefox https://github.com/LLK/scratch-gui/issues/2160 @fsih 
* [x] Non english characters get cut off on the stage when using a font they don’t appear in (example - greek letters in pixel font) everything looks fine in sans serif font @chrisgarrity (https://github.com/LLK/scratch-paint/issues/481) : 
![image6](https://user-images.githubusercontent.com/1088291/40558913-df17775c-6022-11e8-8bcf-da87d17ecaa1.png)
* [x] Pen down on stage? Scratch 2: the stage has clear and no other blocks under pen @BryceLTaylor
* [x] In windows, when you add extensions, or are on a small screen, scroll bars are very frustrating and you can’t read the blocks (https://github.com/LLK/scratch-gui/issues/2215) @fsih 
![image5](https://user-images.githubusercontent.com/1088291/40558933-f8abd53c-6022-11e8-9194-77f6b9114e3f.png)
* [x] Share the love doesn’t work on iOS safari @paulkaplan 
* [x] Can’t get video on in video motion (Windows Firefox) or costume from camera
gui error Unhandled video io device error (https://github.com/LLK/scratch-gui/issues/2216)
MediaStreamError { name: "NotReadableError", message: "Failed to allocate videosource", constraint: "", stack: "" } @fsih 
* [x] Color blocks don’t randomize when switching sprites anymore @kchadha #2209
* [x] Floria project: 223217573 is crazy broken and gives many errors: Uncaught Tried to glow stack on block that does not exist
Error: Tried to serialize a variable field with no variable. @BryceLTaylor
* [x] Cat can move off stage.  Inconsistent with Scratch 2 @BryceLTaylor

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Karishma
Mac | Chrome | Bryce
iPad | Safari | Paul
Chromebook | Chrome | Eric R
Windows* | Firefox | DD
Android Tablet | Chrome |  
Windows* | Edge | Karishma
Mac | Safari | Bryce
Mac | Firefox | ChrisG

**Comment by sjhuang26** [comment]
I'm a bit confused as to how I should contribute to the smoke test.

Why do only a few bugs have links to issues?

Does a check mark mean that this bug is already fixed in a pending pull request?

Each issue has a name next to it. Does that mean that only that person should work on the bug?

**Comment by towerofnix** [comment]
@sjhuang26 I'm pretty sure that smoke tests are basically in-house testing, where a bunch of the people working on Scratch come together and try things in the editor, keeping notes of what problems they come across. Then those are all collected together here. I'm pretty sure the usernames are whoever found that issue; so for example, "Share the love doesn’t work on iOS safari @paulkaplan" means @paulkaplan is the one who spotted the issue.

The checkmarks are for noted problems that now have actual issues; as you see, every item with a checkmark also has a link to the issue. The ones that don't have checkboxes still need issues to be opened (usually by the person who found the problem) or found (if there's already an existing issue for the problem).

**Comment by BryceLTaylor** [comment]
* [X] Make Music video has section where black bars appear in video briefly @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2172
* [X] Pen down on stage? Scratch 2: the stage has clear and no other blocks under pen @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2174
* [X] Floria project: 223217573 is crazy broken and gives many errors: Uncaught Tried to glow stack on block that does not exist
Error: Tried to serialize a variable field with no variable. @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2180
* [X] Cat can move off stage.  Inconsistent with Scratch 2 @BryceLTaylor Unable to reproduce

**Comment by kchadha** [comment]
@BryceLTaylor I have submitted all the issues I could successfully repro, some of them were windows browser specific difficult to repro/describe issues, so I'm leaving them out because they're also pretty minor.
