### ISSUE TITLE
Smoke Test issues from Friday 6/1/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2214]
* [x] The stage can “say”... @paulkaplan Fixed
* [x] Behavior of sharing a block referencing a local variable  with the stage is oddly undefined. No crashes or console errors, variable shows up in the stage toolbox, monitor in stage toolbox is checked (like it was in original sprite), but making changes to variable from the stage seems to no-op @kchadha 
* [x] Workspace comments should have the same font as block comments @kchadha LLK/scratch-blocks#1554
* [x] https://llk.github.io/scratch-gui/smoke/#225695864  crashes on iPad Pro Safari (and also Mac Safari) @rschamp 
* [x] The comment expand icon is too small to tap easily on an iPad Pro at the default zoom level @rschamp 
* [x] Comments appear beyond the edge of workspace, but you cannot scroll to see them fully @carljbowman LLK/scratch-blocks#1554
![image2](https://user-images.githubusercontent.com/1088291/40854985-2a612e96-65a1-11e8-8e60-b5c909508d84.gif)
* [x] I got into a state where none of the scratch-blocks interface was able to be interacted with at all @rschamp 
* [x] You can drag a comment really far outside of the workspace and then can’t scroll to it @rschamp LLK/scratch-blocks#1554
* [x] Not sure if it’s due to comments but on https://llk.github.io/scratch-gui/develop/#226951058 when I try to mouse scroll down over the blocks workspace I scroll up twice as fast instead @fsih https://github.com/LLK/scratch-gui/issues/2220
* [x] Really hard to minimize comments on ipad.  Impossible to make bigger again @BryceLTaylor
* [ ] Minimized comments have a somewhat odd background @paulkaplan 
* [ ] Workspace and blocks palette jump a few pixels when dragging a block @carljbowman 
* [x] Can’t scroll workspace when mouse happens to be over a comment @kchadha LLK/scratch-blocks#1554
* [ ] Putting pick random in language dropdown does not choose a language @paulkaplan 
* [x] Should adding sprites populate selected language in translate block menu with a different random language? @kchadha 
* [x] New variables default to capitalized on the iPad keyboard (to fix: see https://stackoverflow.com/questions/35513968/disable-auto-correct-in-safari-text-input) @rschamp 
* [x] Softkeyboard doesn’t stay open on edge/surface (https://github.com/LLK/scratch-blocks/issues/1345) @chrisgarrity 
* [x] `translate (join (apple) (banana)) to (<language other than english>)` outputs ‘applebanana’ in English. What should it do? @kchadha 
* [x] On the iPad, tapping an item in a thermometer menu displays the tooltip for the item. This looks like something you should click, but clicking it closes the menu without doing anything. @rschamp 
* [ ] On project page of https://scratch.ly/preview/15620986, the #39; in the project description is a link, it isn’t a link on current project page @paulkaplan 
* [ ] Project https://scratch.ly/preview/15620986 when you “see inside” gives lots of console errors @paulkaplan 
* [ ] Text is still off on https://llk.github.io/scratch-gui/develop/compatibility-testing.html#10015857
* [x] Selecting a learning resource by the top bar(blue) causes whatever is below it in the GUI to highlight on ipad @BryceLTaylor
* [x] Text is tiny in videos on ipad @BryceLTaylor
* [x] Youtube full screen button doesn’t fullscreen on ipad @BryceLTaylor
* [ ] Hebrew is not in the dropdown list for translate @paulkaplan 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Paul
Mac | Chrome | Andrew
iPad | Safari | Bryce, Ray (iPad Pro)
Chromebook | Chrome | Carl
Windows* | Firefox | DD
Android Tablet | Chrome | ERic R
Windows* | Edge | ChrisG (surface)
Mac | Safari | KO
Mac | Firefox | Karishma
motox4 | chrome | katelyn

**Comment by BryceLTaylor** [comment]
* [X] Really hard to minimize comments on ipad.  Impossible to make bigger again @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2223
* [X] Selecting a learning resource by the top bar(blue) causes whatever is below it in the GUI to highlight on ipad @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2222
* [X] Text is tiny in videos on ipad @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2221
* [X] Youtube full screen button doesn’t fullscreen on ipad @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2219

**Comment by kchadha** [comment]
* [x] Behavior of sharing a block referencing a local variable  with the stage is oddly undefined. No crashes or console errors, variable shows up in the stage toolbox, monitor in stage toolbox is checked (like it was in original sprite), but making changes to variable from the stage seems to no-op @kchadha #2247
* [ ] Should adding sprites populate selected language in translate block menu with a different random language? @kchadha #2249
* [ ] `translate (join (apple) (banana)) to (<language other than english>)` outputs ‘applebanana’ in English. What should it do? @kchadha #2251

**Comment by rschamp** [comment]
* [x] https://llk.github.io/scratch-gui/smoke/#225695864  crashes on iPad Pro Safari (and also Mac Safari) @rschamp https://github.com/LLK/scratch-gui/issues/2245
* [x] The comment expand icon is too small to tap easily on an iPad Pro at the default zoom level @rschamp (https://github.com/LLK/scratch-gui/issues/2223)
* [x] I got into a state where none of the scratch-blocks interface was able to be interacted with at all @rschamp (https://github.com/LLK/scratch-gui/issues/2255)
* [x] You can drag a comment really far outside of the workspace and then can’t scroll to it @rschamp LLK/scratch-blocks#1554
* [x] New variables default to capitalized on the iPad keyboard (to fix: see https://stackoverflow.com/questions/35513968/disable-auto-correct-in-safari-text-input) @rschamp (https://github.com/LLK/scratch-gui/issues/2256)
* [x] On the iPad, tapping an item in a thermometer menu displays the tooltip for the item. This looks like something you should click, but clicking it closes the menu without doing anything. @rschamp (https://github.com/LLK/scratch-gui/issues/2257)
