### ISSUE TITLE
Smoke Test issue from Friday 6/8/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2296]
Copy your tests into a new comment before checking them off to avoid saving over each other.

* [ ] Problems with the “when this sprite touches” hat on touch: Touch position doesn’t reset when you release, so you can’t touch a sprite and then touch it again (because it was never not touching)  @ericrosenbaum 
* [x] Slow moving “snitch” when telling distance from mouse @BryceLTaylor
* [ ] Scroll bars don’t work in IE https://github.com/LLK/scratch-gui/issues/2285 @fsih 
* [x] Scrolling is weird @kchadha LLK/scratch-blocks#1554
* [ ] When scrolling blocks appear above the zoom controls @carljbowman 
* [ ] On android chrome, loading a project with a comment enables the soft keyboard on load (but not 100% of the time?) @ericrosenbaum 
* [x] On chromebook chrome, sometimes the caret on a minimized comment overlaps the text #2352 @technoboy10 
* [ ] On chromebook chrome, cannot enter edit mode on a block comment by touching @technoboy10 
* [x] Can’t edit the text of a comment in iPad safari (touch issue?) @kchadha  LLK/scratch-blocks#1554
* [ ] On chromebook chrome (tablet mode), keyboard does not pop up on any comment (no editing :( ) @technoboy10 
* [x] Block comments appear later than workspace comments when switching sprites @BryceLTaylor
* [ ] Loading this project (220013521) on Windows Firefox causes the blocks workspace to appear off set @carljbowman 
* [ ] MostOfTheBlocks freezes Edge https://github.com/LLK/scratch-gui/issues/2286 @fsih 
* [x] ‘Set pen color’ > ‘set pen size to 1200’ > ‘pen down’ does not work. Adding move 10 at the end, makes it work... @kchadha #2324
* [ ] Minimize button on comments is really small https://github.com/LLK/scratch-gui/issues/2288 @fsih 
* [ ] Comments are offset in Edge https://github.com/LLK/scratch-gui/issues/2287 @fsih 
* [x] Dragging a sprite on the stage in editor mode switches sprites but does not bring that sprite to the top (should it?) @kchadha #1870 
* [x] Should we re-trigger the when touching hat while it’s running? @BryceLTaylor
* [x] Touching Edge? And touching edge hat are never true if you you are running an if on edge block @BryceLTaylor
* [ ] Pen down doesn’t draw (Edge) https://github.com/LLK/scratch-gui/issues/2289 @fsih 
<del>* [ ] There should be a glide in current direction block (needs discussion?) @kchadha</del>
* [ ] Chromebook chrome: orange sprite gets cut off in library @technoboy10 
* [ ] Dove sprite is not centered in library @kchadha 
* [x] Oops something wrong in workspace after clicking add backdrop https://github.com/LLK/scratch-gui/issues/2292 @chrisgarrity 
* [ ] Touching hat gets “stuck on” when used with a clone @ericrosenbaum 
* [ ] Tentacle is not attached in some of the octopus costumes (Edge) https://github.com/LLK/scratch-gui/issues/2290 @fsih 
* [ ] Paint tool on Android is laggy @ericrosenbaum 
* [x] Scrolling on the side of a library (after having typed in the search bar) drags highlight of text from search bar @kchadha #2378
* [ ] Chromebook chrome: moving a workspace comment causes everything left of the stage to shift around @technoboy10 
* [ ] Edge won’t close ??? https://github.com/LLK/scratch-gui/issues/2291 @fsih 

Costume/Sprite Thumbnail issues add to https://github.com/LLK/scratch-gui/issues/2258
* [ ] Bowtie-a, Bowtie-b, Cake-a Cloud-*, Crystal-*, Dani-c , Dinosaur3-*, Dove-* costumes are not centered in library @kchadha 
* [ ] Dinosaur 2-a costume is smaller than other Dinosaur2-* costumes in costume library @kchadha 
* [ ] Soccer ball, taco sprite not centered in libary @technoboy10 
* [ ] Some costumes cut off in library: orange, hat winter, cake, bear2-a @technoboy10 

Device | Browser | Name
-- | -- | --
Windows* | Chrome |  
Mac | Chrome | Bryce
iPad | Safari | Karishma
Chromebook | Chrome | Connor
Windows* | Firefox | Carl
Android Tablet | Chrome | Eric R
Windows* | Edge | DD
Mac | Safari | Ray
Mac | Firefox | ChrisG
motox4 | chrome |

**Comment by BryceLTaylor** [comment]
* [X] Slow moving “snitch” when telling distance from mouse @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2298
* [X] Block comments appear later than workspace comments when switching sprites @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2299
* [X] Should we re-trigger the when touching hat while it’s running? @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2301
* [X] Touching Edge? And touching edge hat are never true if you you are running an if on edge block @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2300
