### ISSUE TITLE
Smoke Test issue from Friday 6/15/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2381]
To avoid the issue where checking a box at the same time as someone else un-checks their box, please copy your issues into a comment below and check them there.  I'll copy the checks up to the main body of the issue later for easy viewing.

* [ ] Various individuals had trouble uploading projects with lots of assets @ericrosenbaum 
* [x] Scratch.ly asset server test - big lag time between choosing a gif file to upload as a costume from local disk and ‘Uploading’ bar showing up on the stage @kchadha 
* [x] Dragging a costume/sprite tile around the editor highlights things around the editor… (seems to happen for some tiles and not others..?) @kchadha Fixed
![image8](https://user-images.githubusercontent.com/1088291/41547980-a3a9ee54-72ef-11e8-9f91-4145d9beee28.gif)
* [ ] (Chromebook touch only) dragging anything around is very laggy after Chrome thinks it detects a back/forward gesture #2395 @technoboy10 
* [ ] iPad touch dragging sprites/costumes brings the UI around with it @paulkaplan 
* [x] Block comment disappears. Seen on https://llk.github.io/scratch-gui/develop/#226951058 and 223875256. Go to the costume or sound tab and back to the blocks tab. It sometimes takes a couple tries. Firefox. I also reproed in Chrome. @fsih 
* [x] Can’t scroll within long comments @fsih 
* [ ] Caret and close button does not switch to normal (not dragging) cursor on workspace comments #2399 @technoboy10 
* [x] I pasted the entirety of Moby Dick into a comment and it (surprisingly) allowed me to do so. We should probably have a limit. @thisandagain 
* [x] After resizing a block comment the workspace becomes pinned to the bottom right. @carljbowman (resolved in #1591)
* [ ] Comment resizing can make it “inside out” (smaller than minimized comment @ericrosenbaum 
* [x] Switching to a sprite with only comments opens the soft keyboard.(android) https://github.com/LLK/scratch-gui/issues/2387 @chrisgarrity 
* [x] When dragging a comment, the comment looks different (text is thinner, top bar gets lighter) @kchadha 
* [ ] Paint editor numeric value stepper button on windows does not work twice in a row unless you move the mouse (e.g. to change the size of the eraser, you have to click the arrow, then move the mouse before clicking the arrow again) @ericrosenbaum 
* [x] Comment layers get reordered when switching back and forth sprites, which makes the lines stick through the boxes sometimes @fsih 
* [x] Scrolling with the wheel is so slow (firefox) in paint editor @fsih 
* [x] Not sure how I got into this state, but I drew a rectangle, and then resized it, and at some point got into a state where my rectangle was selected, and my mouse was not down, but the rectangle fill was moving with the mouse @kchadha 
![image6](https://user-images.githubusercontent.com/1088291/41548003-b69c52f4-72ef-11e8-9561-6514f38e12d3.gif)
* [ ] When I add a bitmap rectangle, and while it’s still in vector mode, I switch costumes or duplicate costume, the rectangle disappears (maybe it should rasterize immediately) @ericrosenbaum 
* [ ] (Chromebook Chrome, touch + keyboard) The fill color modal is below some other controls (delete backdrop, others) #2394 @technoboy10 
* [x] Fill should have a threshold @fsih 
* [x] Unselected stage toggle button should have a mouse-over color change (to indicate that it is clickable and not disabled) @kchadha 
* [x] It would be nice to still be able to access the other sprite-info fields (via a drop down?) when in small stage mode @kchadha 
* [x] Cursor still changes over list monitor buttons, even though it doesn’t work in fullscreen stage mode @fsih 
![image7](https://user-images.githubusercontent.com/1088291/41548030-c790eb06-72ef-11e8-8f7b-9202efd94856.gif)
* [ ] In small stage mode with scrollbars on, the sprite list wraps to a single sprite in each row @paulkaplan 
* [ ] When toggling between the small stage and regular stage (not full screen), the ‘size’ field in the sprite info pane seems to ‘animate/appear’ slower than everything else @kchadha 
![image10](https://user-images.githubusercontent.com/1088291/41548083-e8d3f98e-72ef-11e8-8d10-e7bc827f6cdb.gif)
* [x] Sprite reverts to full size when dragging a sprite on the small stage size https://github.com/LLK/scratch-gui/issues/2388 @chrisgarrity 
* [x] @fsih 
![image9](https://user-images.githubusercontent.com/1088291/41548115-ffcacb86-72ef-11e8-8f65-2da624599a03.gif)
* [ ] Drag preview is not crisp on hi dpi screens @paulkaplan 
* [ ] Can’t move variables outside a very small region in small stage mode #2367 @technoboy10 
* [ ] Can’t drag list monitor in small stage mode, list monitor always snaps to top left corner on drag in small stage mode #2367 @technoboy10 
* [ ] “Play sound” block, when you drop in something that reports an empty string, should treat it as a 0 (and play the last-indexed sound, which it does in 2.0), but it instead plays nothing @ericrosenbaum 
* [x] Should sound library indicate sound length? Hovering to discover sounds tends to cause you to miss long sounds @fsih 
* [ ] Sometimes still clicking noises when stopping sounds after a rest (Chromebook chrome) https://github.com/LLK/scratch-audio/issues/93 @technoboy10 
* [x] Forever start sound. Would expect it to loop the beginning of the sound, but instead it occasionally starts to click a lot and then plays the whole sound. My sound is length .41s @fsih 

Device | Browser | Name | IP Address | Device-specific task | Assets Trouble
-- | -- | -- | -- | -- | --
Windows* | Chrome | Eric R | 18.85.27.93 | *Ensure that IE gives an error page |  
Mac | Chrome | Carl | 18.85.24.86 |   |  
iPad** | Safari | Paul | 18.85.25.154 | **Ensure that Safari 10 show “welcome” page (i.e. not blank) | Yes
Chromebook | Chrome | Connor | 18.85.26.67 |   |  
Windows* | Firefox | DD | 18.85.25.20 |   |  
Android Tablet | Chrome | ChrisG |   |   | Yes
Windows* | Edge |   |   |   |  
Mac | Safari | Karishma | 18.85.25.178 |   | Yes
Mac | Firefox | Chrisg | 18.85.27.42 |   | Yes
(Sauce)* | IE 11 | Paul | 18.85.25.154 | *Ensure that IE gives an error page |

**Comment by towerofnix** [comment]
> Scrolling with the wheel is so slow (firefox) in paint editor @fsih

See also (but not identical to) LLK/scratch-blocks#1190. I've already made a fix (LLK/scratch-blocks#1427) that can basically be identically applied to scratch-paint.

**Comment by kchadha** [comment]
* [ ] Scratch.ly asset server test - big lag time between choosing a gif file to upload as a costume from local disk and ‘Uploading’ bar showing up on the stage @kchadha
* [x] When dragging a comment, the comment looks different (text is thinner, top bar gets lighter) @kchadha #2463
* [ ] Not sure how I got into this state, but I drew a rectangle, and then resized it, and at some point got into a state where my rectangle was selected, and my mouse was not down, but the rectangle fill was moving with the mouse @kchadha 
![image6](https://user-images.githubusercontent.com/1088291/41548003-b69c52f4-72ef-11e8-9561-6514f38e12d3.gif)
* [x] Unselected stage toggle button should have a mouse-over color change (to indicate that it is clickable and not disabled) @kchadha #2466
* [x] It would be nice to still be able to access the other sprite-info fields (via a drop down?) when in small stage mode @kchadha #2467

**Comment by fsih** [comment]
* [x] Block comment disappears. Seen on https://llk.github.io/scratch-gui/develop/#226951058 and 223875256. Go to the costume or sound tab and back to the blocks tab. It sometimes takes a couple tries. Firefox. I also reproed in Chrome. @fsih **FIXED**
* [x] Can’t scroll within long comments @fsih https://github.com/LLK/scratch-gui/issues/2470
* [x] Comment layers get reordered when switching back and forth sprites, which makes the lines stick through the boxes sometimes @fsih https://github.com/LLK/scratch-gui/issues/2472
* [x] Scrolling with the wheel is so slow (firefox) in paint editor @fsih https://github.com/LLK/scratch-paint/issues/529
* [x] Fill should have a threshold @fsih https://github.com/LLK/scratch-paint/issues/531
* [x] Cursor still changes over list monitor buttons, even though it doesn’t work in fullscreen stage mode @fsih https://github.com/LLK/scratch-gui/issues/2473
* [x] @fsih **FIXED**
![image9](https://user-images.githubusercontent.com/1088291/41548115-ffcacb86-72ef-11e8-8f65-2da624599a03.gif)
* [x] Should sound library indicate sound length? Hovering to discover sounds tends to cause you to miss long sounds @fsih https://github.com/LLK/scratch-gui/issues/2474
* [x] Forever start sound. Would expect it to loop the beginning of the sound, but instead it occasionally starts to click a lot and then plays the whole sound. My sound is length .41s @fsih https://github.com/LLK/scratch-gui/issues/2475
