### ISSUE TITLE
Smoke Test Issue from Friday 6/22/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2443]
Make sure you copy items with your name on it into a new comment to check them off.
Create a new issue or find an existing issue for each item with your name on it.  Link to the issue in your comment.

Also, there are still outstanding issues that need to be filed from previous smoke tests: https://github.com/LLK/scratch-gui/issues/2381 https://github.com/LLK/scratch-gui/issues/2296

* [x] Cannot share costumes/sounds to the stage @paulkaplan (https://github.com/LLK/scratch-gui/issues/2452)
* [x] There is a weird black flash over the costume when you share it with its own sprite, but not when sharing to other sprites. Looks like a bad css transition @paulkaplan 
* [x] Say bubbles seem to default to the left now instead of to the right? May have been an issue for a long time, but just noticed it. Repro: default project => say “hello” @paulkaplan (https://github.com/LLK/scratch-vm/issues/1268)
* [x] (Chrome OS 66) When reordering a sprite, the sprite briefly flashes back to its previous position before going to the right place @technoboy10 
* [x] iOS clicking sound block does not play a sound, and sound editor does not play a sound. Weirdly, after enabling the mic, it works. @ericrosenbaum (https://github.com/LLK/scratch-gui/issues/2453)
* [ ] (Chrome OS 66) Ask dialog checkmark is green and emoji-ish instead of a proper white check mark @technoboy10 
* [ ] On iOS, enable video motion, then disable camera using the button in the URL bar, then re-enable, and now the aspect ratio of the video is incorrect @ericrosenbaum 
* [ ] On iOS, enable video motion, then switch to another tab and load scratch, then switch back. Video is frozen or gray. (can recover by using blocks to turn video off then on again) @ericrosenbaum 
* [x] The baseball and jurassic backdrops thumbnails are messed up in the libraries @carljbowman 
![image11](https://user-images.githubusercontent.com/1088291/41791075-a1b5779a-7622-11e8-938e-3317fa54e598.png)
* [x] Sound blocks look funny @fsih 
![image13](https://user-images.githubusercontent.com/1088291/41791093-b0d0a042-7622-11e8-973d-a6cf6082b42c.png)
* [ ] Sharing blocks with comments does not work: block is shared but not comment – “vm Could not find comment with id:<long string> in provided comment descriptions.” @paulkaplan 
* [x] You can drag a comment by its line? @fsih 
![image17](https://user-images.githubusercontent.com/1088291/41791110-c20a29d2-7622-11e8-96b3-2fe7df65532b.gif)
* [x] New sprites aren’t grouped to be easily poseable (e.g. the skeleton’s arms could be a group) @fsih 
* [x] macOS firefox: change costume block gets real wonky @technoboy10 
![image18](https://user-images.githubusercontent.com/1088291/41791124-d050fa34-7622-11e8-98e2-5069ef1d5945.png)
* [x] (Safari) Dragging a Costume by the text on the tile retmains the text cursor while dragging, this results in text and elements on the page becoming highlighted @carljbowman 
![image19](https://user-images.githubusercontent.com/1088291/41791210-16a43ae6-7623-11e8-9aa9-738439a18102.gif)
* [x] Dragging a costume to another sprite doesn’t give the green glow (the way dragging code does) @fsih 
![image20](https://user-images.githubusercontent.com/1088291/41791250-36063c4a-7623-11e8-8fa6-60732f57f11e.gif)
* [x] Workspace comments have text in them that you must manually delete before you can type. (block comments don’t.) @BryceLTaylor
* [x] After editing a comment, whenever I switch sprites away and then back to the sprite with a comment, the keyboard pops up and the comment has focus @rschamp 
* [x] I can’t drag costumes to other sprites  — the sprite lights up like it can receive the costume, but it doesn’t actually receive It looks like that but the actual behavior is that the costume can only be dropped into the currently selected sprite @rschamp 
* [x] (Chrome OS 66) Transparent ovals turn black after exiting edit mode @technoboy10 
* [x] After typing an emoji and resizing it, the emoji disappears from the editor (Chrome OS 66, macOS Firefox) @technoboy10 
* [x] By undoing, got into a state where I’m in the eraser tool but there’s still an oval in select mode @fsih 
![image15](https://user-images.githubusercontent.com/1088291/41791277-4f2f6778-7623-11e8-8300-20f9a8f6b06d.png)
* [x] Creating a large emoji in the vector paint editor and then converting to bitmap results in the emoji disappearing @thisandagain 
* [x] Creating a large emoji in the bitmap editor disappears after entering the emoji @rschamp  
* [x] How to videos appear off the editor way down here @fsih 
![image16](https://user-images.githubusercontent.com/1088291/41791306-5f7aeb02-7623-11e8-9152-58aa1ade5d47.png)
* [x] On my tablet I have to scroll down to see the whole editor. The add from library buttons only activate if I touch the area visible when the page loads, before scrolling down to view the bottoms of the buttons. @rschamp 
* [x] What are serifs @fsih https://github.com/LLK/scratch-gui/issues/1961
![image12](https://user-images.githubusercontent.com/1088291/41791349-7b94c75e-7623-11e8-95f1-c6eccef3bf8c.png) 
* [x] Videos are a bit out of date (search icon now in thermometers) @fsih 
* [ ] Forever play drum for 0 beats creates a loud sharp sound @ericrosenbaum 
* [x] Click the stack on the rightClick the stack on the leftAs soon as you click the stack on the left, the cymbal sound plays. In Scratch 2 it stops the current sound, but not the next ones (once you pop, you can’t stop) @fsih 
![image14](https://user-images.githubusercontent.com/1088291/41791392-9e0873e4-7623-11e8-8c14-a4a44cdcc076.png)
* [x] When sprites/costumes/bgs/sounds are being dragged, the dimensions of of the underlying tile element are not square, but rather are the ratio of the artwork. We should make the tile square while dragging to have a closer relation to the tile in the sprite/costume/bg/sound lists. @carljbowman

**Comment by BryceLTaylor** [comment]
* [x] Workspace comments have text in them that you must manually delete before you can type. (block comments don’t.) @BryceLTaylor https://github.com/LLK/scratch-gui/issues/2456

**Comment by BryceLTaylor** [comment]
Forgot to add who was using which OS/Browser:


Device | Browser | Name
-- | -- | --
Windows* | Chrome | ChrisG
Mac | Chrome | Bryce
iPad** | Safari | Eric R
Chromebook | Chrome | Connor
Windows* | Firefox | DD
Android Tablet | Chrome | Ray
Windows* | Edge |  
Mac | Safari | Carl
Mac | Firefox | Connor
(Sauce) | IE 11 | Paul
(Sauce) | Safari 10 | Paul

**Comment by kchadha** [comment]
* [x] After editing a comment, whenever I switch sprites away and then back to the sprite with a comment, the keyboard pops up and the comment has focus @rschamp LLK/scratch-blocks#1601

**Comment by fsih** [comment]
* [x] Sound blocks look funny @fsih https://github.com/LLK/scratch-gui/issues/2476
![image13](https://user-images.githubusercontent.com/1088291/41791093-b0d0a042-7622-11e8-973d-a6cf6082b42c.png)
* [x] You can drag a comment by its line? @fsih https://github.com/LLK/scratch-gui/issues/2477
![image17](https://user-images.githubusercontent.com/1088291/41791110-c20a29d2-7622-11e8-96b3-2fe7df65532b.gif)
* [x] New sprites aren’t grouped to be easily poseable (e.g. the skeleton’s arms could be a group) @fsih https://github.com/LLK/scratch-gui/issues/2478
* [x] Dragging a costume to another sprite doesn’t give the green glow (the way dragging code does) @fsih https://github.com/LLK/scratch-gui/issues/2479
![image20](https://user-images.githubusercontent.com/1088291/41791250-36063c4a-7623-11e8-8fa6-60732f57f11e.gif)
* [x] By undoing, got into a state where I’m in the eraser tool but there’s still an oval in select mode @fsih 
![image15](https://user-images.githubusercontent.com/1088291/41791277-4f2f6778-7623-11e8-8300-20f9a8f6b06d.png) https://github.com/LLK/scratch-gui/issues/2480
* [x] How to videos appear off the editor way down here @fsih https://github.com/LLK/scratch-gui/issues/2154
![image16](https://user-images.githubusercontent.com/1088291/41791306-5f7aeb02-7623-11e8-9152-58aa1ade5d47.png)
* [x] What are serifs @fsih https://github.com/LLK/scratch-gui/issues/1961
![image12](https://user-images.githubusercontent.com/1088291/41791349-7b94c75e-7623-11e8-95f1-c6eccef3bf8c.png) 
* [x] Videos are a bit out of date (search icon now in thermometers) @fsih https://github.com/LLK/scratch-gui/issues/2481
* [x] Click the stack on the rightClick the stack on the leftAs soon as you click the stack on the left, the cymbal sound plays. In Scratch 2 it stops the current sound, but not the next ones (once you pop, you can’t stop) @fsih https://github.com/LLK/scratch-gui/issues/2482
![image14](https://user-images.githubusercontent.com/1088291/41791392-9e0873e4-7623-11e8-8c14-a4a44cdcc076.png)

**Comment by rschamp** [comment]
* [x] After editing a comment, whenever I switch sprites away and then back to the sprite with a comment, the keyboard pops up and the comment has focus @rschamp https://github.com/LLK/scratch-blocks/issues/1601
* [x] I can’t drag costumes to other sprites  — the sprite lights up like it can receive the costume, but it doesn’t actually receive It looks like that but the actual behavior is that the costume can only be dropped into the currently selected sprite @rschamp https://github.com/LLK/scratch-gui/issues/2484
* [x] Creating a large emoji in the bitmap editor disappears after entering the emoji @rschamp  https://github.com/LLK/scratch-paint/issues/534
* [x] On my tablet I have to scroll down to see the whole editor. The add from library buttons only activate if I touch the area visible when the page loads, before scrolling down to view the bottoms of the buttons. @rschamp https://github.com/LLK/scratch-gui/issues/2485

**Comment by carljbowman** [comment]
* [x] The baseball and jurassic backdrops thumbnails are messed up in the libraries @carljbowman ![image11](https://user-images.githubusercontent.com/1088291/41791075-a1b5779a-7622-11e8-938e-3317fa54e598.png) https://github.com/LLK/scratch-gui/issues/2487
* [x] (Safari) Dragging a Costume by the text on the tile retmains the text cursor while dragging, this results in text and elements on the page becoming highlighted @carljbowman https://github.com/LLK/scratch-gui/issues/2489
* [x] When sprites/costumes/bgs/sounds are being dragged, the dimensions of of the underlying tile element are not square, but rather are the ratio of the artwork. We should make the tile square while dragging to have a closer relation to the tile in the sprite/costume/bg/sound lists. @carljbowman 
https://github.com/LLK/scratch-gui/issues/2490

**Comment by technoboy10** [comment]
* [x] (Chrome OS 66) When reordering a sprite, the sprite briefly flashes back to its previous position before going to the right place @technoboy10 https://github.com/LLK/scratch-gui/issues/2498
* [x] macOS firefox: change costume block gets real wonky @technoboy10 https://github.com/LLK/scratch-gui/issues/2502
* [x] (Chrome OS 66) Transparent ovals turn black after exiting edit mode @technoboy10 https://github.com/LLK/scratch-paint/issues/535
* [x] After typing an emoji and resizing it, the emoji disappears from the editor (Chrome OS 66, macOS Firefox) @technoboy10 https://github.com/LLK/scratch-paint/issues/534
