### ISSUE TITLE
File Issues found in recent smoke tests from June 

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2565]
Please file or mark as filed/won't file/duplicate/etc. each issue found in a recent smoketest listed below.  Included in each is who found the original issue in the smoke test and the date of the smoke test. 

These were not marked as filed in the issue for the smoke test they were found in.

* [x] Minimized comments have a somewhat odd background @paulkaplan  6/1 [won't file]
* [x] On android chrome, loading a project with a comment enables the soft keyboard on load (but not 100% of the time?) @ericrosenbaum  6/8 [mentioned in a comment on LLK/scratch-blocks#1601]
* [x] On chromebook chrome, cannot enter edit mode on a block comment by touching @technoboy10  6/8 [LLK/scratch-blocks#1631]
* [x] On chromebook chrome (tablet mode), keyboard does not pop up on any comment (no editing :( ) @technoboy10  6/8 LLK/scratch-blocks#1631
* [x] Comments are offset in Edge https://github.com/LLK/scratch-gui/issues/2287 @fsih  6/8
* [x] Chromebook chrome: moving a workspace comment causes everything left of the stage to shift around @technoboy10  6/8 [won't file -- this issue was resolved]
* [x] Caret and close button does not switch to normal (not dragging) cursor on workspace comments #2399 @technoboy10  6/15
* [x] Comment resizing can make it “inside out” (smaller than minimized comment @ericrosenbaum  6/15 LLK/scratch-blocks#1630
* [x] We should show an error message when uploading the wrong file type @fsih 6/29 #2717
* [x] Costume tile ‘x’ button displays on top of with color picker menu @kchadha [#2672]
