### ISSUE TITLE
File Issues found in recent smoke tests from June

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2568]
Please file or mark as filed/won't file/duplicate/etc. each issue found in a recent smoketest listed below. Included in each is who found the original issue in the smoke test and the date of the smoke test.

These were not marked as filed in the issue for the smoke test they were found in.

* [x] Paint tool on Android is laggy @ericrosenbaum  https://github.com/LLK/scratch-paint/issues/575 6/8
* [x] Paint editor numeric value stepper button on windows does not work twice in a row unless you move the mouse (e.g. to change the size of the eraser, you have to click the arrow, then move the mouse before clicking the arrow again) @ericrosenbaum  6/15 https://github.com/LLK/scratch-paint/issues/576
* [ ] When I add a bitmap rectangle, and while it’s still in vector mode, I switch costumes or duplicate costume, the rectangle disappears (maybe it should rasterize immediately) @ericrosenbaum  6/15
* [x] (Chromebook Chrome, touch + keyboard) The fill color modal is below some other controls (delete backdrop, others) #2394 @technoboy10  6/15
* [x] Text is still off on https://llk.github.io/scratch-gui/develop/compatibility-testing.html#10015857 6/1 https://github.com/LLK/scratch-render/issues/215
* [x] Tentacle is not attached in some of the octopus costumes (Edge) https://github.com/LLK/scratch-gui/issues/2290 @fsih  6/8
* [x] It’s a bit jarring that the selected element disappears from the stage after moving (or making any transformation) with the select tool. (+1 paul) @carljbowman 6/29 https://github.com/LLK/scratch-paint/pull/569

**Comment by fsih** [comment]
@ericrosenbaum can you check if your bug #3 above still reproes? I'm not sure I understand the repro steps
