### ISSUE TITLE
File Issues found in recent smoke tests from June

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2569]
Please file or mark as filed/won't file/duplicate/etc. each issue found in a recent smoketest listed below. Included in each is who found the original issue in the smoke test and the date of the smoke test.

These were not marked as filed in the issue for the smoke test they were found in.

* [x] Project https://scratch.ly/preview/15620986 when you “see inside” gives lots of console errors @paulkaplan  6/1 https://github.com/LLK/scratch-www/issues/1963
* [x] On project page of https://scratch.ly/preview/15620986, the #39; in the project description is a link, it isn’t a link on current project page @paulkaplan  6/1 https://github.com/LLK/scratch-api/issues/509
* [x] When the on screen keyboard is popped up and then dismissed, full screen stays small @technoboy10 6/29 https://github.com/LLK/scratch-gui/issues/2581
