### ISSUE TITLE
File Issues found in recent smoke tests from June

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2570]
Please file or mark as filed/won't file/duplicate/etc. each issue found in a recent smoketest listed below. Included in each is who found the original issue in the smoke test and the date of the smoke test.

These were not marked as filed in the issue for the smoke test they were found in.

* [ ] In small stage mode with scrollbars on, the sprite list wraps to a single sprite in each row @paulkaplan  6/15
* [ ] When toggling between the small stage and regular stage (not full screen), the ‘size’ field in the sprite info pane seems to ‘animate/appear’ slower than everything else @kchadha  6/15
![image10](https://user-images.githubusercontent.com/1088291/41548083-e8d3f98e-72ef-11e8-8d10-e7bc827f6cdb.gif)
* [ ] Can’t move variables outside a very small region in small stage mode #2367 @technoboy10  6/15
* [ ] Can’t drag list monitor in small stage mode, list monitor always snaps to top left corner on drag in small stage mode #2367 @technoboy10  6/15
* [ ] Pen down doesn’t draw (Edge) https://github.com/LLK/scratch-gui/issues/2289 @fsih  6/8
