### ISSUE TITLE
Issues found in Smoke Test on Friday 7/13

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2623]
Please file or mark as filed/won't file/duplicate/etc. each issue.

* [x] Fonts don’t look the same in sprite/costume thumbnails @kchadha https://github.com/LLK/scratch-gui/issues/2762
* [x] On iPad mini, switching to the Costumes tab causes the stage/sprite info to get shifted 10 pixels to the right. Code and Sound tabs do not cause this shift. @carljbowman https://github.com/LLK/scratch-gui/issues/2763
* [x] Random dot on topmost paint editor layer... @kchadha https://github.com/LLK/scratch-paint/issues/262
* [x] Bitmap select, move the selection, change sprite/costume/tab, come back and what was selected is gone @paulkaplan https://github.com/LLK/scratch-paint/issues/566
* [x] Eyedropper crashes the GUI when using it on an iPad - possible OOM (Out of Memory) @carljbowman  (might already have issue) https://github.com/LLK/scratch-paint/issues/577
* [x] Resize svg on import feature??? @BryceLTaylor https://github.com/LLK/scratch-paint/issues/578
* [x] On Android, eyedropper button doesn’t do anything @ericrosenbaum https://github.com/LLK/scratch-paint/issues/579

Device | Browser | Name
-- | -- | --
Windows | Chrome | Paul
Mac | Chrome | Bryce
iPad | Safari | Carl
Chromebook | Chrome | Andrew
Windows* | Firefox | DD
Android Tablet | Chrome | Eric R
Windows* | Edge |  
Mac | Safari | Karishma
Mac | Firefox | ChrisG
