### ISSUE TITLE
Issues found in Smoke Test on Friday 7/13

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2628]
Please file or mark as filed/won't file/duplicate/etc. each issue.

* [ ] Toolbar is breaking responsively on iPad mini. The username wraps and appears outside the nav container, this causes the entire GUI to horizontally scrollable @carljbowman 
* [ ] Borders aren’t fully rendered on a couple of sprites
In the all the blocks project, when entering numbers @chrisgarrity 
![image8](https://user-images.githubusercontent.com/1088291/42706389-9c9f65b2-86a4-11e8-8539-d8de38479bbf.png)
* [ ] On touch (on android) long press to duplicate a stack, then the blocks tab is frozen (can recover by e.g. switching sprites) @ericrosenbaum 
* [ ] On Android, it loads in browser full-screen mode, but after I delete a sprite or costume etc, it exits full-screen mode but does not resize the editor, so there’s a blank space at the bottom (might be due to using a native alert to confirm delete?) @ericrosenbaum 

Device | Browser | Name
-- | -- | --
Windows | Chrome | Paul
Mac | Chrome | Bryce
iPad | Safari | Carl
Chromebook | Chrome | Andrew
Windows* | Firefox | DD
Android Tablet | Chrome | Eric R
Windows* | Edge |  
Mac | Safari | Karishma
Mac | Firefox | ChrisG

**Comment by BryceLTaylor** [comment]
* [ ] sharing a duplicated block with a variable to a new sprite grabs the sprite icon and doesn't copy the code. @BryceLTaylor also Oliver

**Comment by BryceLTaylor** [comment]
* [x] Toolbar is breaking responsively on iPad mini. The username wraps and appears outside the nav container, this causes the entire GUI to horizontally scrollable @carljbowman https://github.com/LLK/scratch-gui/issues/2641
* [x] Borders aren’t fully rendered on a couple of sprites
In the all the blocks project, when entering numbers @chrisgarrity 
![image8](https://user-images.githubusercontent.com/1088291/42706389-9c9f65b2-86a4-11e8-8539-d8de38479bbf.png)
https://github.com/LLK/scratch-gui/issues/2642

**Comment by BryceLTaylor** [comment]
* [x] On touch (on android) long press to duplicate a stack, then the blocks tab is frozen (can recover by e.g. switching sprites) @ericrosenbaum https://github.com/LLK/scratch-blocks/issues/1647
* [x] On Android, it loads in browser full-screen mode, but after I delete a sprite or costume etc, it exits full-screen mode but does not resize the editor, so there’s a blank space at the bottom (might be due to using a native alert to confirm delete?) @ericrosenbaum https://github.com/LLK/scratch-gui/issues/2644

**Comment by BryceLTaylor** [comment]
* [ ] sharing a duplicated block with a variable to a new sprite grabs the sprite icon and doesn't copy the code. @BryceLTaylor also Oliver https://github.com/LLK/scratch-gui/issues/2645
