### ISSUE TITLE
Issues found in 8/10/18 Smoke Test

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2883]
* [ ] The dinosaur does _not_ make it to the back @technoboy10 
* [ ] Weird stuff going on w/nexus tablet in full screen mode, loading screen did not cover the full gui layout @kchadha 
* [ ] Soft keyboard on Nexus tablet covers a lot of the variable modal @kchadha 
* [ ] Custom procedures modal on Nexus tablet -- adding a parameter or a label pops up the soft keyboard for a second and then it immediately goes away @kchadha 
* [ ] Share the love does not work on android tablet @kchadha 
* [ ] https://llk.github.io/scratch-gui/develop/#92357585 never loads on edge @fsih 
* [ ] Project doesn’t load:
https://llk.github.io/scratch-gui/develop/#108641277
Error: Failed to load project from server [id=#108641277]: Error: Cannot create monitor for target that cannot be found by name
    at e.value (lib.min.js:41)
@chrisgarrity 
* [ ] “Pen Football” project runs much slower than in 2.0. Also, it runs slower when the pen sprite (tons of blocks, glowing and unglowing rapidly) is showing than when the stage is showing (no blocks): https://llk.github.io/scratch-gui/develop/#103746364
Also in numerous tries I was only able to score a single goal in “professional” mode (working as expected)
@ericrosenbaum 
* [ ] Pen project performance in Firefox and Safari is noticeably worse than in Chrome @technoboy10 
* [ ] https://llk.github.io/scratch-gui/develop/#105186001 does not load in Scratch 3.0 with error `TypeError: "this._svgTag.getBBox is not a function" 	value` @technoboy10 
* [ ] 238746871 looks worse on develop than beta @kchadha 
* [ ] Typing text in vector mode, the blinking cursor is not where you are typing (sticky to the left of the textbox) @kathymakes 
* [ ] Text-tool in paint doesn’t open soft keyboard @chrisgarrity 
* [ ] Eye dropper doesn’t work with touch (MS surface) @chrisgarrity 
* [ ] Restored sprite with local variable monitor checked doesn’t show the variable (monitor save & load) @chrisgarrity 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | chrisG
Mac | Chrome | Bryce
iPad** | Safari | kathy
Chromebook | Chrome | Eric R
Windows* | Firefox | Ray
Android Tablet | Chrome | Karishma
Windows* | Edge | DD
Mac | Safari | Carl
Mac | Firefox | Connor
(Sauce) | IE 11 |  
(Sauce) | Safari 10 |
