### ISSUE TITLE
Issues found in 8/10/18 Smoke Test

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2888]
* [x] Gray bar on left edge of sound/costume editors in RTL on Nexus Tablet @kchadha #2800
* [x] RTL: layout buttons don’t match layout  @fsih #2800
![image32](https://user-images.githubusercontent.com/1088291/44227570-f7230580-a160-11e8-9c58-8a0c0b8a8216.png)
* [x] Boolean responses not translated (true, false) @technoboy10 [blocks#1685](https://github.com/LLK/scratch-blocks/issues/1685)
* [x] Should > and < flip in  Hebrew?
https://lists.freedesktop.org/archives/libreoffice/2012-March/028506.html suggests that those signs should flip in RTL language @BryceLTaylor - Not true for Hebrew. Translators need to do the "right" thing by reordering arguments.
* [x] Hebrew tutorials appeared somewhere weird @BryceLTaylor #2758
* [x] Hebrew layout: dropdown for languages goes off the screen @kathymakes #2757
* [ ] Extension library tile for translate extension should not have “Google” transliterated in Hebrew (?) @ericrosenbaum - I'm checking with Moran on this one. One issue is that mixed RTL and LTR text is always painful.
* [x] Text curls up in hebrew @fsih 
[]([](![image24](https://user-images.githubusercontent.com/1088291/44227820-9b0cb100-a161-11e8-95a9-6e1bd84f8a48.png))) [blocks#1684](https://github.com/LLK/scratch-blocks/issues/1684)
* [x] Tutorial cards show up off the screen in Hebrew @technoboy10 #2758
![image31](https://user-images.githubusercontent.com/1088291/44227905-d60ee480-a161-11e8-9ad6-a1eaa5a6f92a.png)
* [x] Is this colon in the right spot? @fsih 
![image40](https://user-images.githubusercontent.com/1088291/44227941-efb02c00-a161-11e8-8adc-23de08e76ced.png) [blocks#1683](https://github.com/LLK/scratch-blocks/issues/1683)
* [x] Paintbrush icon is flipped RTL for costumes tab, but remains LTR in the other menus @kathymakes #2800 
* [x] Block dropdown menus in RTL look left-aligned @kathymakes [blocks#1675](https://github.com/LLK/scratch-blocks/issues/1675)
* [x] Current… month, day, year… the menu items are not translatable @kchadha  @chrisgarrity - I think these were just not yet translated.

Device | Browser | Name
-- | -- | --
Windows* | Chrome | chrisG
Mac | Chrome | Bryce
iPad** | Safari | kathy
Chromebook | Chrome | Eric R
Windows* | Firefox | Ray
Android Tablet | Chrome | Karishma
Windows* | Edge | DD
Mac | Safari | Carl
Mac | Firefox | Connor

**Comment by chrisgarrity** [comment]
There are issues for everything except the transliteration of 'Google'. From Moran on whether names (e.g. Scratch) should be left in English: 

> Especially with RTL languages, leaving English words reduces the readability quite a lot, so - we don’t tend to leave word in English in the middle of sentences in Hebrew, because it’s very weird to read :slightly_smiling_face: Instead, we just use a phonetic translation.
