### ISSUE TITLE
Issues found in 8/17/18 Smoke Test

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2903]
* [x] Win Edge on touch (surface), tapping the add sprite/backdrop/costume/sound button always opens the library, so I am unable to use the other options @ericrosenbaum https://github.com/LLK/scratch-gui/issues/3025
* [x] I tried to scroll and accidentally dragged out a block from somewhere. This is probably related to the scrolling happening super slow. @LiFaytheGoblin https://github.com/LLK/scratch-gui/issues/3028
* [x] I expected a normal zoom gesture to actually change the size of the scripts but it just scrolled. @LiFaytheGoblin  https://github.com/LLK/scratch-gui/issues/3031
* [x] Text on the alltheblocks backdrop for full screen dragging is cut off @chrisgarrity https://github.com/LLK/scratch-vm/issues/1477
* [x] Dragging and dropping a sprite around the stage which is mostly just text on a transparent backdrop is hard because with my finger I have a hard time touching the exact thin line to move it @LiFaytheGoblin https://github.com/LLK/scratch-gui/issues/3029
* [x] Win Edge on touch (surface), when I drag out a wait block and click the input to edit the number of seconds, the soft keyboard opens and then immediately closes, so I am unable to use it. @ericrosenbaum https://github.com/LLK/scratch-blocks/issues/1345
* [x] I accidentally zoomed the whole editor to be bigger by double clicking the green flag @LiFaytheGoblin Won't file (see below)
* [x] Trying to use the scroll bars does not work well on mobile, actually I haven’t managed to scroll. It somehow doesn’t select the scrollbar. The intuitive finder move for scrolling will just work like a mouse click and move. When trying to first click the scrollbar to then move it I selected the scrollbar and got the option of copying it. @LiFaytheGoblin https://github.com/LLK/scratch-gui/issues/3030

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl
Mac | Chrome | Bryce
iPad** | Safari | Ray
Chromebook | Chrome | ChrisG
Windows* | Firefox | DD
Android Tablet | Chrome | Linda
Windows* | Edge | Eric R (on surface)
Mac | Safari | Kathy
Mac | Firefox | Karishma

**Comment by BryceLTaylor** [comment]
* [ ] I accidentally zoomed the whole editor to be bigger by double clicking the green flag @LiFaytheGoblin 

I could not reproduce this and I'm not sure exactly what you mean.  It's possible that you somehow pinched to zoom.  We'll keep an eye out for it though.

**Comment by BryceLTaylor** [comment]
All filed
