### ISSUE TITLE
Issues found in 8/17/18 Smoke Test

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2907]
* [x] Score text has black outline in 3.0 and is fuzzy in 2.0
Menu button should not have weird rectangle around it
https://llk.github.io/scratch-gui/smoke/#220986096 @fsih 
* [x] Color picker in the Paint Editor does not work in the GUI when it loaded within WWW @carljbowman  https://github.com/LLK/scratch-www/issues/2030
* [x] Scrollbars in the paint editor are a bit small @carljbowman  https://github.com/LLK/scratch-paint/issues/611
* [x] Win Edge on touch, no paint editor scroll bars appear even when zoomed in (no console errors) @ericrosenbaum  https://github.com/LLK/scratch-paint/issues/612
* [x] On iPad mini, tapping and holding a scroll bar causes a gray overlay to appear over the left half of the screen. Trying to drag them causes the entire page to scroll slightly @rschamp https://github.com/LLK/scratch-paint/issues/613

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl
Mac | Chrome | Bryce
iPad** | Safari | Ray
Chromebook | Chrome | ChrisG
Windows* | Firefox | DD
Android Tablet | Chrome | Linda
Windows* | Edge | Eric R (on surface)
Mac | Safari | Kathy
Mac | Firefox | Karishma
