### ISSUE TITLE
Issues from Smoke Test 8/24/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2992]
* [x] Does the t in “After it’s been clicked” look bold?  [Zooming in, it looks like the t is a tiny bit thicker than the i next to it (approx 8 pixels vs 7 when I view it fullscreen); our sampling method for resizing may distort this small difference -Ben] @rschamp https://github.com/LLK/scratch-render/issues/143
![image61](https://user-images.githubusercontent.com/1088291/44663280-14b46280-a9de-11e8-857e-d27369757df8.png)
* [x] Zoom controls in paint editor are not aligned with paint canvas (same behavior in both LTR and RTL) @kchadha https://github.com/LLK/scratch-paint/issues/637
* [x] Paint Editor: Had fill tool selected. Zoomed in, wanted to scroll, accidentally used fill tool on vector object. Can’t revert, thumbnail still shows the old color of the object. Then I acccidentally clicked somewhere and suddenly the object is back in it’s old color again. @LiFaytheGoblin https://github.com/LLK/scratch-paint/issues/638
* [x] Filling the owl-b costume with two different gradients fills some other parts of the owl with black on the stage (eye and breast). (Undo/Redo also changes the parts that are black) @chrisgarrity https://github.com/LLK/scratch-paint/issues/639
![image54](https://user-images.githubusercontent.com/1088291/44663445-93110480-a9de-11e8-80c8-4f9631a8dfea.png)
![image58](https://user-images.githubusercontent.com/1088291/44663405-770d6300-a9de-11e8-9876-c47e42945248.png)
* [x] Gradient icons in the color picker become black when you choose one of the gradient types @kathymakes @carljbowman https://github.com/LLK/scratch-paint/issues/640
![image36](https://user-images.githubusercontent.com/1088291/44663470-a6bc6b00-a9de-11e8-9c81-ee98c13da86e.png)
* [x] Highlighted text in the paint editor looks vertically offset https://github.com/LLK/scratch-paint/issues/437 @kathymakes @carljbowman 
![image51](https://user-images.githubusercontent.com/1088291/44663542-e2efcb80-a9de-11e8-9279-5b8ef342a7c8.png) (included a note that it was a known issue)
* [x] On iPad, cursor is in the wrong place in the text tool in the paint editor (when the gui language is in Korean…? But it’s not clear that the gui language actually affects this change) @kchadha 
(See google doc for .gif, it's huge and github doesn't like it/) https://github.com/LLK/scratch-paint/issues/488
* [x] Vector editor: Can not use the eraser over a text @LiFaytheGoblin LLK/scratch-paint#406
* [x] Scaling text huge in vector mode and then typing a lot sends you flying off the editor (see scrollbar below)…. Weee @kathymakes 
![image46](https://user-images.githubusercontent.com/1088291/44663959-e59ef080-a9df-11e8-9c68-623ed3fff812.gif) https://github.com/LLK/scratch-paint/issues/641

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl / Kathy
Mac | Chrome | Bryce
iPad** | Safari | Karishma
Chromebook | Chrome |  
Windows* | Firefox | DD
Android Tablet | Chrome | Linda
Windows* | Edge |  
Mac | Safari | Ray
Mac | Firefox | ChrisG

**Comment by apple502j** [comment]
llk/scratch-paint#406
"Vector editor: Can not use the eraser over a text"

**Comment by fsih** [comment]
Does the t in “After it’s been clicked” look bold? [Zooming in, it looks like the t is a tiny bit thicker than the i next to it (approx 8 pixels vs 7 when I view it fullscreen); our sampling method for resizing may distort this small difference -Ben] @rschamp

I think this is an instance of https://github.com/LLK/scratch-render/issues/143
