### ISSUE TITLE
Issues found in Smoke Test (Bug Hunt) on 8/31/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3068]
* [x] @fsih https://github.com/LLK/scratch-blocks/issues/1684
![image18](https://user-images.githubusercontent.com/1088291/45052334-82066a00-b054-11e8-891f-0ea7556ca1ac.png)
![image19](https://user-images.githubusercontent.com/1088291/45052343-8a5ea500-b054-11e8-81b7-27ad63de69ec.png)
![image25](https://user-images.githubusercontent.com/1088291/45052355-934f7680-b054-11e8-82ad-b317558a9bf5.png)
![image29](https://user-images.githubusercontent.com/1088291/45052373-9ea2a200-b054-11e8-9812-b9697d079ed1.png)
![image24](https://user-images.githubusercontent.com/1088291/45052388-a7937380-b054-11e8-8ee1-27ea5bd9c254.png)

* [x] Rtl: monitors that have no location should default to the right, not to the left @LiFaytheGoblin https://github.com/LLK/scratch-gui/issues/3126
* [x] None of the labels for the Custom Procedure module are translated in any language @BryceLTaylor https://github.com/LLK/scratch-gui/issues/3059
* [x] Should this icon (on the left) also match the speaker icons? @kathymakes 
![image17](https://user-images.githubusercontent.com/1088291/45052459-dc9fc600-b054-11e8-802e-554630999978.png)
No. This is the echo effect and it corresponds to the way the echo appears on the audio stream. The Audio stream is supposed to be LTR.
* [x] In RTL, in the device connection modal, in the “connecting” step, the “split button” shapes are not correctly flipped @chrisgarrity https://github.com/LLK/scratch-gui/issues/3127
* [x] The “x” in the dimension for costumes is at the beginning of the string? @kathymakes 
![image20](https://user-images.githubusercontent.com/1088291/45052505-ffca7580-b054-11e8-96be-1178e8526c68.png) https://github.com/LLK/scratch-gui/issues/3128

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Eric R
Mac | Chrome | ChrisG
iPad** | Safari | Bryce
Chromebook | Chrome | Bryce
Windows* | Firefox | Carl
Android Tablet | Chrome | Linda
Windows* | Edge | DD
Mac | Safari |  
Mac | Firefox | Kathy
