### ISSUE TITLE
Issues found in Bug Hunt (smoke test) on 9/7/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3095]
* [x] Can’t draw or use any tool more than a dot on edge with touch.  Not on Android.  Not on Chrome/touch @BryceLTaylor https://github.com/LLK/scratch-paint/issues/396
* [x] Firefox mac: delete in paint editor asks if you want to stay or leave on the page (i.e. delete invokes the back button behavior in the browser). Chrome doesn’t. @kathymakes https://github.com/LLK/scratch-paint/issues/663
* [x] On Chromebook, when editing a backdrop, copy a bitmap backdrop, switch to an empty vector backdrop, paste. The pasted image shows up with its top-left at the center (i.e. incorrectly positioned- this may only be visible when you switch to another backdrop and back), and the pasted image does not appear on the stage at all. @ericrosenbaum https://github.com/LLK/scratch-paint/issues/664
* [x] After changing the font of a text area in the paint editor, undo fixes the look of the text, but doesn’t update the chosen font in the dropdown @rschamp https://github.com/LLK/scratch-paint/issues/665
* [x] It might be nice to have “group” be command-G. (more of an expert feature maybe. It’s common in adobe products/vector edit tools) @kathymakes https://github.com/LLK/scratch-gui/issues/3067
* [x] Soft Keyboard doesn’t appear when creating a text box (not a problem with chrome).  Then it did later.  Then it didn’t. @BryceLTaylor https://github.com/LLK/scratch-paint/issues/666
* [x] The font Marker doesn’t do weird characters such as German Umlaute. Instead it puts another weird symbol! Eg trying to make a c cedille will lead to an uppercase A with an accent grave being displayed. In bitmap, the c cedille leads to <<. The choice of which letter to display instead of the wanted letter seems partly different in ltr and rtl. @LiFaytheGoblin 
* [x] All keyboard shortcuts work on Windows Firefox *except* for CMD+Shift+Z (redo) @thisandagain https://github.com/LLK/scratch-paint/issues/667
* [x] When typing in Hebrew in the paint editor, the cursor is sometimes in the wrong place. If I type ששש, the cursor jumps back by two characters @ericrosenbaum https://github.com/LLK/scratch-paint/issues/668
* [x] Mouth is filled with transparent in paint and looks black on stage @fsih 
![image10](https://user-images.githubusercontent.com/1088291/45235290-6abebb00-b2a6-11e8-9ff3-ceaaf9a5cd4d.png) https://github.com/LLK/scratch-paint/issues/669

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl
Mac | Chrome | Ray
iPad** | Safari | Linda
Chromebook | Chrome | Eric R
Windows* | Firefox | Andrew
Android Tablet | Chrome | Ben
Windows* | Edge | Bryce (on surface), DD
Mac | Safari | kathy
Mac | Firefox | katelyn
(Sauce) | IE 11 | DD

**Comment by fsih** [comment]
The font Marker doesn’t do weird characters such as German Umlaute. Instead it puts another weird symbol! Eg trying to make a c cedille will lead to an uppercase A with an accent grave being displayed. In bitmap, the c cedille leads to <<. The choice of which letter to display instead of the wanted letter seems partly different in ltr and rtl. @LiFaytheGoblin

Unfortunately this is working as intended; many of the fonts don't support many languages. Our aim was to replace fonts with fonts that looked "close" to the 2.0 fonts while supporting *more* languages, and try to have most languages work in at least one font, but unique-looking fonts often support very few languages.
