### ISSUE TITLE
Issues found in Bug Hunt and Clay Test on 9/14/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3152]
* [x] [bug hunt] Can’t scroll paint editor with touch on android touch @BryceLTaylor https://github.com/LLK/scratch-paint/issues/703
* [x] [bug hunt] Can’t reshape costume after starting in select tool, selecting entire sprite, switching to reshape tool, and trying to drag one of the points to reshape. Need to un-select and re-select the sprite with the reshape tool selected to be able to reshape. @kchadha https://github.com/LLK/scratch-paint/issues/690
* [x] [bug hunt] Mac Safari gave me a warning that the webpage is “using significant energy”: 
(I had made a costume with a bunch of copies of a vector building, so that it was >1000px wide, and was playing with scrolling it around) @ericrosenbaum 
![image22](https://user-images.githubusercontent.com/1088291/45646677-0bc12900-ba92-11e8-85ef-f781de2c511f.png)
* [x] [clay test] When moving the imported image on Stage it will temporarily cut it [at]Carmelo https://github.com/LLK/scratch-gui/issues/1808
![image12](https://user-images.githubusercontent.com/1088291/45646785-5642a580-ba92-11e8-981f-1f7628a7530e.gif)
* [x] [clay test] Setting the rotation center of circle3, then circle2, return to circle3, and the rotation center has reset to the original center.  @chrisgarrity https://github.com/LLK/scratch-paint/issues/647
![image10](https://user-images.githubusercontent.com/1088291/45646846-7a9e8200-ba92-11e8-8f52-5eade807c77b.gif)
* [x] [clay test] When I undo something when erasing -- even if I have set the eraser size to something new - it will revert to the previous size @kathymakes https://github.com/LLK/scratch-paint/issues/706
* [x] Bitmap editor automatically clips out the parts of the images that go out of the frame.  @seotts https://github.com/LLK/scratch-gui/issues/1808

bug hunt:
Device | Browser | Name
-- | -- | --
Windows* | Chrome | Chris WF, Ben
Mac | Chrome | Carl
iPad** | Safari | Ray
Chromebook | Chrome | ChrisG
Windows* | Firefox |  
Android Tablet | Chrome | Bryce
Windows* | Edge | DD
Mac | Safari | Eric R
Mac | Firefox | Karishma

clay test

Device | Browser | Name
-- | -- | --
Windows* | Chrome |  
Mac | Chrome | ChrisG, Karishma
Chromebook | Chrome | Bryce
Windows* | Firefox |  
Windows* | Edge |  
Mac | Safari | Eric R, Carl
Mac | Firefox | Linda
