### ISSUE TITLE
Issues found in Bug Hunt and Clay Test on 9/14/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3154]
* [x] [bug hunt] The monitor for the “backdrop name” block imported from 2.0 shows up blank (the block gets correctly imported as the new “backdrop [number, name]” block, but the monitor itself not converted) @ericrosenbaum [Filed in LLK/scratch-vm#1628]
Seems possibly related to LLK/scratch-vm#1513
* [x] [bug hunt] In small screen mode, the costume number monitor became weirdly wrapped. In normal screen mode it takes up one line. I would expect it to still take up 1 line. Project 246339451 @fsih [Filed in #3267]
![image18](https://user-images.githubusercontent.com/1088291/45648929-dc151f80-ba97-11e8-8d7b-4e9d14ce1608.png)
* [x] [bug hunt] When you drag monitors, it works but your cursor is the text edit cursor. I would expect hand or at least pointer @fsih [Filed in #3268]
* [x] [bug hunt] After uploading a file, the file menu stays open @fsih 
![image15](https://user-images.githubusercontent.com/1088291/45648987-0666dd00-ba98-11e8-83f3-32ab1bd68d20.png) [Already filed in #2525]
* [x] [clay test] When the stage is small due to resizing the browser or clicking the small-stage button, monitors can’t be moved to the bottom or right edges of the stage. @cwillisf [Already filed in #2367]
* [x] [clay test] Stacks that use “when I start as clone” and a “forever” look do not stack highlight when running @carljbowman [Filed in LLK/scratch-vm#1629]
* [x] [clay test] It’s a little hard to see because of the gif artifacts, but the animation gets very jerky when in full screen. The project uses 100 clones. I have the project saved. @chrisgarrity 
![image11](https://user-images.githubusercontent.com/1088291/45649059-44640100-ba98-11e8-97f8-86214d898544.gif) [This issue is already fixed on beta]
* [x] [clay test] If you have a project running (mine uses ‘if key pressed’ in a loop under the green flag clicked hat), and you add a backdrop *using the library* (this step is very important), the project stops reacting to key presses until you switch back to the blocks tab. This is not the case w/adding a surprise backdrop for example. @kchadha [Filed in #3269]
* [x] [clay test] Downloading was weird. I had a project with 61 costumes in a sprite that were from photos so probably pretty big. Only after hitting download many times after some time with delay the download dialog showed up. @LiFaytheGoblin [Filed in #3271]

bug hunt:

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Chris WF, Ben
Mac | Chrome | Carl
iPad** | Safari | Ray
Chromebook | Chrome | ChrisG
Windows* | Firefox |  
Android Tablet | Chrome | Bryce
Windows* | Edge | DD
Mac | Safari | Eric R
Mac | Firefox | Karishma

clay test:

Device | Browser | Name
-- | -- | --
Windows* | Chrome |  
Mac | Chrome | ChrisG, Karishma
Chromebook | Chrome | Bryce
Windows* | Firefox |  
Windows* | Edge |  
Mac | Safari | Eric R, Carl
Mac | Firefox | Linda
