### ISSUE TITLE
Issues found in Bug Hunt and Clay Test on 9/14/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3156]
* [x] [bug hunt] On Mac Safari (and iOS Safari), ask prompt check mark is not being rendered correctly (it’s too large and not centered): @ericrosenbaum  https://github.com/LLK/scratch-gui/issues/2924
![image19](https://user-images.githubusercontent.com/1088291/45649260-d3711900-ba98-11e8-80ac-83cf87145fcf.png)
* [x] [bug hunt] Check looks a little cut off on the right and bottom edges @fsih  https://github.com/LLK/scratch-gui/issues/2924
![image21](https://user-images.githubusercontent.com/1088291/45649357-129f6a00-ba99-11e8-9526-2d10148fdcc5.png)
* [x] [clay test] Paint Editor: It’s easy to lose the rotation handle if the shape is either halfway off the canvas or near the bottom of the canvas @carljbowman  https://github.com/LLK/scratch-paint/issues/747
![image8](https://user-images.githubusercontent.com/1088291/45649400-3498ec80-ba99-11e8-8085-a620cba8635b.gif)
* [x] [clay test] Paint Editor: There are a few different types of bezier curve points. We default to “Disjointed”, should we consider switching to “Asymmetric” @carljbowman 
![image7](https://user-images.githubusercontent.com/1088291/45649417-411d4500-ba99-11e8-8bd2-9c6b6acb56f8.gif) https://github.com/LLK/scratch-paint/issues/748
* [x] [clay test] I want to be able to upload gifs! OR multiple costumes at once! Or better: both! @LiFaytheGoblin https://github.com/LLK/scratch-gui/issues/3541
* [x] [clay test] If there are no sounds, sound tab is empty. Looks unintentional? https://github.com/LLK/scratch-gui/issues/3156 @kathymakes 
![image6](https://user-images.githubusercontent.com/1088291/45649462-5eeaaa00-ba99-11e8-87cc-cea7deae4dee.png)

bug hunt:
Device | Browser | Name
-- | -- | --
Windows* | Chrome | Chris WF, Ben
Mac | Chrome | Carl
iPad** | Safari | Ray
Chromebook | Chrome | ChrisG
Windows* | Firefox |  
Android Tablet | Chrome | Bryce
Windows* | Edge | DD
Mac | Safari | Eric R
Mac | Firefox | Karishma

clay test

Device | Browser | Name
-- | -- | --
Windows* | Chrome |  
Mac | Chrome | ChrisG, Karishma
Chromebook | Chrome | Bryce
Windows* | Firefox |  
Windows* | Edge |  
Mac | Safari | Eric R, Carl
Mac | Firefox | Linda

**Comment by fsih** [comment]
[clay test] Paint Editor: There are a few different types of bezier curve points. We default to “Disjointed”, should we consider switching to “Asymmetric” @carljbowman 

The handles shouldn't be disjointed by default. When you make a new point, the handles are always stuck parallel to each other until you adjust them holding alt. Is this an imported shape?
