### ISSUE TITLE
Issues found in Bug Hunt on 9/21

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3216]
* [x] I switched from english to dutch and many things were translated. Fallback was english. I switched to Maori and fallback was dutch. I would expect the fallback to be english. (Fallback means the language the editor uses when no translation in the currently chosen langage is available) @LiFaytheGoblin [Talked with @LiFaytheGoblin and this the same monitor problem below:  https://github.com/LLK/scratch-vm/issues/1279]
* [x] Switching back to english from Hebrew caused the extension monitors to be partially translated. @BryceLTaylor https://github.com/LLK/scratch-vm/issues/1279
![image32](https://user-images.githubusercontent.com/1088291/45958870-8506d180-bfe6-11e8-8bd0-9a0660a03aab.png)
* [x] Menu language in block remains the previous language you set @kathymakes 
![image29](https://user-images.githubusercontent.com/1088291/45959035-f0e93a00-bfe6-11e8-9a7f-6cd6a9d67ec1.png) https://github.com/LLK/scratch-vm/issues/1365 (fixed)
* [x] Ask and wait block: In one language, execute the ask block. The prompt entry field appears on the stage. Don’t stop the execution. Switch to a different language. The prompt is gone but the block still looks like it is being executed. Clicking stop and restarting the block will show the prompt again. https://github.com/LLK/scratch-vm/issues/1641@LiFaytheGoblin 
* [x] Loading animation in Hebrew, also in firefox @fsih #3311
![image20](https://user-images.githubusercontent.com/1088291/45959094-18400700-bfe7-11e8-9d77-08c46799e192.png)

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Ray
Mac | Chrome | Linda
iPad** | Safari | Ben
Chromebook | Chrome | Eric R
Windows* | Firefox | Kathy
Android Tablet | Chrome |  
Windows* | Edge | DD
Mac | Safari | Bryce
Mac | Firefox | Colby

**Comment by chrisgarrity** [comment]
@LiFaytheGoblin can you show me how to see the issue you reported - I'm not seeing it.
