### ISSUE TITLE
Issues found in Bug Hunt on 9/28/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3282]
* [ ] Some block stacks disappear while running this test project in Mac OS Safari 12:https://llk.github.io/scratch-gui/smoke/#105500895 @thisandagain 
* [ ] https://llk.github.io/scratch-gui/smoke/#15200040 I was in the blocks tab, went to the costumes tab, went back and got a oops, something went wrong in the scripts area @LiFaytheGoblin 
* [ ] https://llk.github.io/scratch-gui/smoke/#55574144 hacked blocks project crashes after briefly showing the beta modal. @chrisgarrity 
* [ ] Loading https://llk.github.io/scratch-gui/smoke/#15200040 followed by https://llk.github.io/scratch-gui/smoke/#105250254 leads to a display of the first project’s workspace with the second project’s stage  @rschamp 
![image30](https://user-images.githubusercontent.com/1088291/46353885-3c28cb80-c62b-11e8-950a-e4e62489c269.png)
* [ ] Lots of js console errors on https://llk.github.io/scratch-gui/smoke/#15200040 :
Uncaught Tried to glow stack on block that does not exist.
gui  Error: Workspace Update Error: Tried to serialize a variable field with no variable.
More weird variable errors…
To replicate, try running and placing multiple types of towers several times; click green flag and do it again; switch to costumes tab and back.
(on Mac Chrome) @benjiwheeler 
* [ ] https://scratch.ly/preview/1000015546/ gives an Oops page with errors in the console: “Cannot read property data of null” and “Cannot read property assetId of null” @kchadha 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl
Mac | Chrome | ChrisG, Evelyn
iPad** | Safari | Eric R
Chromebook | Chrome | Bryce
Windows* | Firefox | DD
Android Tablet | Chrome | katelyn
Windows* | Edge | Ben? (Could use someone else)
Mac | Safari | Andrew, Karishma
Mac | Firefox | Ray, Linda
