### ISSUE TITLE
Issues found in Bug Hunt on 9/28/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3284]
* [x] Android tablet, chrome: Microbit LED field editor clear all doesn’t work @picklesrus 
* [x] 211917681 doesn’t load on android tablet in chrome. End up with aww snap page. @picklesrus 
* [x] 211917681 takes a long time to load (Goomble Gurt) @BryceLTaylor @rschamp
* [x] On MacOS Safari, project 211917681 failed to load. Error: “Error: Failed to load project from server [id=#211917681]: TypeError: Invalid attempt to destructure non-iterable instance” @thisandagain 
* [x] On iOS Safari, project 211917681 failed to load (safari gave me a white screen with “A problem repeatedly occurred”) @ericrosenbaum 
* [x] On iOS safari, project 105250254 shows sprite tiles incorrectly: @ericrosenbaum 
![image35](https://user-images.githubusercontent.com/1088291/46354586-f1a84e80-c62c-11e8-9172-79a2606c2b7b.png)
* [x] Edge does not respond when loading https://llk.github.io/scratch-gui/smoke/#15200040 (loads for a long time, then pops up intro modal, but stuck in spinning blue hula hoop mouse cursor, and Edge eventually shows “Not responding” tip at bottom of screen) @benjiwheeler 
* [x] Scrolling in the paint editor when zoomed in on an adroid tablet doesn’t seem possible.  I can get the scrollbar to notice that I’ve touched it (it turns blue, but it doesn’t follow my finger) @picklesrus 
* [x] Two finger scrolling to the left in the paint editor calls the back action in the browser @BryceLTaylor 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl
Mac | Chrome | ChrisG, Evelyn
iPad** | Safari | Eric R
Chromebook | Chrome | Bryce
Windows* | Firefox | DD
Android Tablet | Chrome | katelyn
Windows* | Edge | Ben? (Could use someone else)
Mac | Safari | Andrew, Karishma
Mac | Firefox | Ray, Linda

**Comment by BryceLTaylor** [comment]
* [ ] 211917681 doesn’t load on android tablet in chrome. End up with aww snap page. @picklesrus 
* [ ] 211917681 takes a long time to load (Goomble Gurt) @BryceLTaylor @rschamp
* [ ] On MacOS Safari, project 211917681 failed to load. Error: “Error: Failed to load project from server [id=#211917681]: TypeError: Invalid attempt to destructure non-iterable instance” @thisandagain 
* [ ] On iOS Safari, project 211917681 failed to load (safari gave me a white screen with “A problem repeatedly occurred”) @ericrosenbaum

**Comment by BryceLTaylor** [comment]
* [x] Edge does not respond when loading https://llk.github.io/scratch-gui/smoke/#15200040 (loads for a long time, then pops up intro modal, but stuck in spinning blue hula hoop mouse cursor, and Edge eventually shows “Not responding” tip at bottom of screen) @benjiwheeler 
https://github.com/LLK/scratch-vm/issues/1658

**Comment by BryceLTaylor** [comment]
* [x] Scrolling in the paint editor when zoomed in on an adroid tablet doesn’t seem possible.  I can get the scrollbar to notice that I’ve touched it (it turns blue, but it doesn’t follow my finger) @picklesrus 
https://github.com/LLK/scratch-paint/issues/703

**Comment by BryceLTaylor** [comment]
* [x] Android tablet, chrome: Microbit LED field editor clear all doesn’t work @picklesrus 

https://github.com/LLK/scratch-gui/issues/3384

**Comment by BryceLTaylor** [comment]
* [ ] On iOS safari, project 105250254 shows sprite tiles incorrectly: @ericrosenbaum

Unable to Reproduce on 10/16.  We should keep an eye out for it.  I did see it happen with just the stage on mac chrome and wrote that up here: https://github.com/LLK/scratch-gui/issues/3383

**Comment by BryceLTaylor** [comment]
* [x]  Two finger scrolling to the left in the paint editor calls the back action in the browser @BryceLTaylor
I opened this as a needs discussion issue. https://github.com/LLK/scratch-gui/issues/3387
