### ISSUE TITLE
Issues found in Bug Hunt on 9/28/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3287]
* [x] Project freezes with errors in console: https://pastebin.com/TYLnRadA @fsih https://github.com/LLK/scratch-gui/issues/3517
* [x] Hit targets for the Bezier curve handles (diamonds) feel small. They are hard to click and drag. +1 @carljbowman https://github.com/LLK/scratch-paint/issues/737
* [x] You can choose a transparent outline + non-0 stroke width and draw shapes with these settings @rschamp https://github.com/LLK/scratch-paint/issues/738
* [x] “You can set strokes on a thing that shouldn’t have a stroke and that probably shouldn’t happen” @kchadha https://github.com/LLK/scratch-paint/issues/739
* [x] A way to get stroke width with transparent stroke @fsih https://github.com/LLK/scratch-paint/issues/740
![image25](https://user-images.githubusercontent.com/1088291/46355860-9fb4f800-c62f-11e8-9c2f-f55e8a00d891.gif)
* [x] You can choose a transparent outline + non-0 stroke, and draw lines. The lines appear as 1px black, so the outline color should appear to be black @rschamp https://github.com/LLK/scratch-paint/issues/738

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Carl
Mac | Chrome | ChrisG, Evelyn
iPad** | Safari | Eric R
Chromebook | Chrome | Bryce
Windows* | Firefox | DD
Android Tablet | Chrome | katelyn
Windows* | Edge | Ben? (Could use someone else)
Mac | Safari | Andrew, Karishma
Mac | Firefox | Ray, Linda
