### ISSUE TITLE
Issues found in Bug Hunt on 10/12/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3369]
* [x] Scrolling the block workspace with the trackpad in RTL on MacOS Firefox causes odd “boucing” behavior (test project 230672117) @thisandagain [Filed in LLK/scratch-blocks#1788]
* [x] Loaded 226779931, with ?locale=ar and then switched to english.  The comments stayed on the left side of the blocks @BryceLTaylor [Filed in #3800]
* [x] https://llk.github.io/scratch-gui/smoke/?locale=ar#115870836 The comment is off the edge? @paulkaplan [Filed in #1789]
![image1](https://user-images.githubusercontent.com/1088291/46960570-d72e9600-d06c-11e8-93a7-a68d6430b2b1.png)
* [ ] Attachment line on a comment sits on top of the stage while dragging comments around. Easier to notice in RTL.  Windows Chrome. @picklesrus [Not an issue?]
* [x] In 226779931 if you load it in English and then switch to Arabic the first two block comments switch to the left side of the blocks, but the bottom ones don’t @BryceLTaylor @kathymakes [Filed in #3801]
* [x] When I create a comment in arabic and switch to English, the comment “attaches” the righthand side of the block but is still positioned to the left (so it covers the block partially)  (Windows firefox) @kathymakes [Included in previous issues mentioned w/(Arabic => English)/(English => Arabic)]
* [x] I loaded a project with comments in hebrew directly using the URL param. Initially, the comment was correctly placed to the left of a stack. But after switching sprites away and back to it, the comment was incorrectly place on the right side of the stack. 
llk.github.io/scratch-gui/smoke?lang=he#238765337 @ericrosenbaum [Filed in 3802]
* [x] When the cloned cats turn a corner or get shot by the arrow, it lags the project  (Windows firefox) @kathymakes [Filed in #3803]
* [x] On Mojave/Firefox, playing a few rounds of #71816138 causes browser tab to freeze. No console output giving any indications. (kevin) [Filed in #3803]

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Katelyn
Mac | Chrome | Karishma
iPad** | Safari | Chrisg
Chromebook | Chrome | Eric R
Windows* | Firefox | kathy
Android Tablet | Chrome |  
Windows* | Edge | Ben
Mac | Safari | Bryce
Mac | Firefox | Andrew
