### ISSUE TITLE
Issues found in Bug Hunt and Play Test on 10/12/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3370]
* [x] (Bug Hunt) Text created in RTL mode in paint editor acts weird when you switch back to LTR language and edit it again @fsih https://github.com/LLK/scratch-paint/issues/741
* [x] (Play Test) (Windows Chrome) Reshape tool doesn’t work to edit shapes that are on top of bitmaps in vector editor @fsih https://github.com/LLK/scratch-paint/issues/742
* [x] (Play Test) (not sure which browser) Issues with copy/pasting multiple bitmap components into a blank vector costume, one component becomes not real… @kchadha https://github.com/LLK/scratch-paint/issues/743
![image1](https://user-images.githubusercontent.com/1088291/46962987-891c9100-d072-11e8-917e-f714ad9065b5.gif)

(Bug Hunt)
Device | Browser | Name
-- | -- | --
Windows* | Chrome | Katelyn
Mac | Chrome | Karishma
iPad** | Safari | Chrisg
Chromebook | Chrome | Eric R
Windows* | Firefox | kathy
Android Tablet | Chrome |  
Windows* | Edge | Ben
Mac | Safari | Bryce
Mac | Firefox | Andrew
