### ISSUE TITLE
Issues found in Bug Hunt on 10/19/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3451]
* [x] Stop other scripts when an ask and wait is running removes the ask input but does not clear speech balloon: @ericrosenbaum [Filed in #3932
![image7](https://user-images.githubusercontent.com/1088291/47315467-a7eeca80-d612-11e8-803b-f5995b63d89c.gif)
* [x] Watermark alignment is slightly different from sprite tile- this coin sprite is not centered in the watermark the same way (#244249375): @ericrosenbaum [Filed in #3933]
![image6](https://user-images.githubusercontent.com/1088291/47315503-c5bc2f80-d612-11e8-9612-2560e16eaa44.gif)
* [x] 91723110  is not working for me in Windows Firefox.  Bryce: it loads but clicking the green flag doesn’t cause any visual difference in the project.  Stacks start glowing in the blocks, though.  Also true on Mac Firefox, Mac Chrome, and on preview @kathymakes [Not an issue -- change hadn't gone in when we tested]
* [x] Multiple issues with the nail polish project: https://llk.github.io/scratch-gui/smoke/#118805754
Press clear button, the pressing C to clear doesn’t work [Filed in #3934]
The sprite with no name (?!?) has a comment that seems to cause a scrolling issue [Already filed in LLK/scratch-blocks#1625]
Kathy: I am having the same issue in windows firefox @ericrosenbaum @kathymakes 
* [x] Also issues with nail polish: https://llk.github.io/scratch-gui/smoke/#118805754
Clear button doesnt work. Blocks are being executed, but dont function @knandersen [Filed in #3934]

Device | Browser | Name
-- | -- | --
Windows* | Chrome | DD
Mac | Chrome | Eric R
iPad** | Safari | ChrisG
Chromebook | Chrome | Paul
Windows* | Firefox | Kathy
Android Tablet | Chrome | Kevin @knandersen
Windows* | Edge | Ben
Mac | Safari | Katelyn, Karishma
Mac | Firefox | Bryce
