### ISSUE TITLE
Issues found in Bug Hunt and Play Test on 10/26/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3556]
* [x] Bug Hunt: Clicking a costume procedure definition or executing the procedure with “run without screen refresh” on should execute at the same speed: @thisandagain 
![image15](https://user-images.githubusercontent.com/1088291/47671695-89468180-db86-11e8-879c-c74f15134138.png)
* [x] Bug Hunt: @fsih [Filed in #4138]
![image14](https://user-images.githubusercontent.com/1088291/47671729-a0856f00-db86-11e8-96e5-f390a0e5ef4d.png)
* [x] Play Test: Toggling on the monitor video motion in 2.0, saving, and opening the project in 3.0: the monitor does not appear and the video motion extension is not added @carljbowman [Not a bug - This is the same as 2.0 -- reloading the 2.0 project in 2.0 also doesn't turn the video back on]
* [x] Play Test:  The workspace fights you when you try to gesture scroll it vertically. There is a block comment on the workspace. Exists on both Smoke and Beta. Project used to test: #255620430 [Filed in LLK/scratch-blocks#1788]
![image7](https://user-images.githubusercontent.com/1088291/47671861-e80bfb00-db86-11e8-8e5a-ead36e1d984e.gif)
* [x] Play Test: Safari hates stack glow (blocks disappear) @BryceLTaylor [Filed in LLK/scratch-blocks#1188]
* [x] Play Test: When I try to scroll down the blocks list (looks, for example) the scroll forces me back upwards. Similar to carl’s bug but in the blocks list @kathymakes [Filed in LLK/scratch-blocks#1788]
* [x] Play Test: 2.0 comment data loaded into vm data and then saved onto the server seems to cause a 500. 
I isolated the remix problem with https://scratch.ly/preview/26069997 -- the issue seems to be the 2.0 detatched comments on the first sprite. If you get rid of those, then remixing (which POSTs to the projects server) succeeds. @benjiwheeler 
[This seems to actually be a problem with the sprite named `stage` which is explicitly not allowed in the sb3 schema in scratch-parser. Tracking this in LLK/scratch-parser#49]

Bug Hunt: 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Ben
Mac | Chrome | FORBIDDEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
iPad** | Safari | Bryce
Chromebook | Chrome | Eric R!!!!!!!!! ChrisG
Windows* | Firefox | Karishma (Surface)
Android Tablet | Chrome | Kathy!!!!
Windows* | Edge | DDDDDDDDDDDDDDDDDDDDD
Mac | Safari | Ray (I don’t have a different device)
Mac | Firefox | Andrew!!!!!
(Sauce) | IE 11 | DD
(Sauce) | Safari 10 | katelyn

Play Test:

Device | Browser | Name
-- | -- | --
Windows* | Chrome | DD
Mac | Chrome | FORBIDDEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
iPad** | Safari | Bryce
Chromebook | Chrome | Chrisg
Windows* | Firefox | DD
Android Tablet | Chrome | Kathy again
Windows* | Edge | DD
Mac | Safari | Karishma, Carl
Mac | Firefox | Ben
(Sauce) | IE 11 | DD

**Comment by kchadha** [comment]
@thisandagain, I can't tell if the first item on this list is still an issue...

copy-pasted from above:
> * [ ] Bug Hunt: Clicking a costume procedure definition or executing the procedure with “run without screen refresh” on should execute at the same speed: @thisandagain 
![image15](https://user-images.githubusercontent.com/1088291/47671695-89468180-db86-11e8-879c-c74f15134138.png)

**Comment by thisandagain** [comment]
@kchadha It is fixed! 🎉
