### ISSUE TITLE
Issues found in Bug Hunt and Play Test on 10/26/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3560]
* [x] Bug Hunt: This whole row is gone! You know how there’s usually tabs, and a green flag? (Windows Chrome, https://llk.github.io/scratch-gui/smoke/#16795490, にほんご language) @fsih 
![image19](https://user-images.githubusercontent.com/1088291/47672574-c449b480-db88-11e8-8e63-631b1acaef78.png)
* [x] Play Test: Bouncy heroes is crazy slow https://llk.github.io/scratch-gui/smoke/#255620430 @benjiwheeler 
* [x] Play Test: You’ve got Chex Mixed doesn’t load on the ipad
* [x] Play Test: This project is behaving differently on 2.0, smoke, and beta… 13911786 @kchadha 
* [x] Play Test: The cat’s mouth is black in the costume tile, it shouldn’t be. @kchadha 

Bug Hunt: 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Ben
Mac | Chrome | FORBIDDEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
iPad** | Safari | Bryce
Chromebook | Chrome | Eric R!!!!!!!!! ChrisG
Windows* | Firefox | Karishma (Surface)
Android Tablet | Chrome | Kathy!!!!
Windows* | Edge | DDDDDDDDDDDDDDDDDDDDD
Mac | Safari | Ray (I don’t have a different device)
Mac | Firefox | Andrew!!!!!
(Sauce) | IE 11 | DD
(Sauce) | Safari 10 | katelyn

Play Test:

Device | Browser | Name
-- | -- | --
Windows* | Chrome | DD
Mac | Chrome | FORBIDDEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
iPad** | Safari | Bryce
Chromebook | Chrome | Chrisg
Windows* | Firefox | DD
Android Tablet | Chrome | Kathy again
Windows* | Edge | DD
Mac | Safari | Karishma, Carl
Mac | Firefox | Ben
(Sauce) | IE 11 | DD

**Comment by Kenny2github** [comment]
> FORBIDDEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> Eric R!!!!!!!!!
> Kathy!!!!
> DDDDDDDDDDDDDDDDDDDDD
> Andrew!!!!!
> FORBIDDEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Did someone drink too much?

**Comment by BryceLTaylor** [comment]
* [x] Bug Hunt: This whole row is gone! You know how there’s usually tabs, and a green flag? (Windows Chrome, https://llk.github.io/scratch-gui/smoke/#16795490, にほんご language) @fsih

https://github.com/LLK/scratch-gui/issues/3572

* [x]  Play Test: The cat’s mouth is black in the costume tile, it shouldn’t be. @kchadha

I believe this is the same issue as this one: https://github.com/LLK/scratch-paint/issues/639

**Comment by BryceLTaylor** [comment]
* [x]  Play Test: This project is behaving differently on 2.0, smoke, and beta… 13911786 @kchadha

https://github.com/LLK/scratch-render/issues/366

**Comment by BryceLTaylor** [comment]
* [x] Play Test: Bouncy heroes is crazy slow https://llk.github.io/scratch-gui/smoke/#255620430 @benjiwheeler

Tracked here:
https://github.com/LLK/scratch-vm/issues/741

**Comment by BryceLTaylor** [comment]
* [x] Play Test: You’ve got Chex Mixed doesn’t load on the ipad

https://github.com/LLK/scratch-gui/issues/3578
