### ISSUE TITLE
Issue found in Bug Hunt on 11/2/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3637]
* [x] https://github.com/LLK/scratch-paint/issues/743 I took a picture with the webcam, and wanted to trim it. I selected part of it in the bitmap editor, but I want to delete everything else, but there’s no way to do that (I couldn’t use select-all because I’m using touch). So I copied the selection, deleted the costume, and added a new one (which creates a vector costume). I pasted in the copied bitmap region of my photo. The costume appears blank in the costume tile and on the stage. I can’t select it in the bitmap editor to move it. @ericrosenbaum 
![image30](https://user-images.githubusercontent.com/1088291/48020086-016ef300-e103-11e8-8d96-e662ef264d59.png)
* [x] https://github.com/LLK/scratch-paint/issues/766 Fading to transparent uploaded sprite loads with black tint in renderer (beta) @fsih 
![image12](https://user-images.githubusercontent.com/1088291/48020178-3c712680-e103-11e8-82e8-fa4082b8feec.png)
```
<svg height="447" version="1.1" width="126" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<defs>
		<linearGradient gradientUnits="userSpaceOnUse" id="color-1" x1="180" x2="180" y1="-34" y2="413">
			<stop offset="0" stop-color="#e3b5ff" stop-opacity="0"/>
			<stop offset="1" stop-color="#e3b5ff"/>
		</linearGradient>
	</defs>
	<g transform="translate(-180,34)">
		<g data-paper-data="{&quot;isPaintingLayer&quot;:true}" fill="url(#color-1)" fill-rule="nonzero" font-family="none" font-size="none" font-weight="none" stroke="none" stroke-dasharray="" stroke-dashoffset="0" stroke-linecap="round" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="1" style="mix-blend-mode: normal" text-anchor="none">
			<path d="M207,70l-12,-46l-15,-58l126,1l-15,53l-11,39l8,354l-81,-9z" id="ID0.6209787102416158"/>
		</g>
	</g>
</svg>
```

* [x] CAN'T REPRO Line sprite is not showing up in thumbnails (beta) @fsih 
![image5](https://user-images.githubusercontent.com/1088291/48020218-5dd21280-e103-11e8-8fcf-a2cb4ebf54df.png)
* [x] https://github.com/LLK/scratch-gui/issues/3748 Scratch-elefant not showing up on stage when uploaded, shows 0x0 size (beta) @fsih 
![image7](https://user-images.githubusercontent.com/1088291/48020239-76422d00-e103-11e8-8899-43319171f02d.png)
* [x] https://github.com/LLK/scratch-paint/issues/767 I was able to get the text to be cut off while using the “Marker” font with diacritics. @thisandagain 
![image13](https://user-images.githubusercontent.com/1088291/48020349-b7d2d800-e103-11e8-8798-eeaf7380d308.png)
![image3](https://user-images.githubusercontent.com/1088291/48020354-bc978c00-e103-11e8-841c-4adf547679e1.png)
* [x] https://github.com/LLK/scratch-paint/issues/641 Text edit cursor appears above the editor border when your font is huge. @kathymakes 
![image14](https://user-images.githubusercontent.com/1088291/48020406-d76a0080-e103-11e8-99be-b179352903bc.gif)
* [x] Edge: Text (in marker font) that I entered in vector disappeared from stage when switching BACK to vector from bitmap.  Entering more text causes the old text to reappear.  After doing that again, I lost the ability to type into a text field in the paint editor (in vector)
Then I drew a line with the paint brush and switched back to the text tool and it I COULD type again. @BryceLTaylor https://github.com/LLK/scratch-paint/issues/770
* [x] https://github.com/LLK/scratch-paint/issues/758 Pixel art is blurry. It used to be crisp @fsih 
![image2](https://user-images.githubusercontent.com/1088291/48020462-f5cffc00-e103-11e8-947b-03b809402803.png)
* [x] https://github.com/LLK/scratch-paint/issues/768 Should we try to cap the stroke lower? Weird things happen if you go over 3 digit values… @kathymakes 
![image15](https://user-images.githubusercontent.com/1088291/48020513-1304ca80-e104-11e8-87c2-bcfb53024116.gif)
* [x] https://github.com/LLK/scratch-paint/issues/769 On Android Tablet Chrome: converting scratch cat costumes to bitmap looks super erroneous @benjiwheeler 
![image29](https://user-images.githubusercontent.com/1088291/48020577-3fb8e200-e104-11e8-9319-4480aa54314a.jpg)
![image26](https://user-images.githubusercontent.com/1088291/48020585-45162c80-e104-11e8-970f-771f57b00fbb.jpg)
![image27](https://user-images.githubusercontent.com/1088291/48020593-49dae080-e104-11e8-95ec-c31b922374c3.jpg)
* [x] https://github.com/LLK/scratch-render/issues/233 Stroke is getting subtly cut off by some kind of bounding box. (pretty sure on the stage) @kathymakes 
![image17](https://user-images.githubusercontent.com/1088291/48020654-7131ad80-e104-11e8-9b3a-44329952732e.png)

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Eric R
Mac | Chrome | ChrisG
iPad** | Safari | Karishma
Chromebook | Chrome | Carl
Windows* | Firefox | DD
Android Tablet | Chrome | Ben
Windows* | Edge | Bryce
Mac | Safari | Andrew
Mac | Firefox | kathy

**Comment by Kenny2github** [comment]
> * [ ]  Should we try to cap the stroke lower? Weird things happen if you go over 3 digit values… @kathymakes
>   ![image15](https://user-images.githubusercontent.com/1088291/48020513-1304ca80-e104-11e8-87c2-bcfb53024116.gif)

HA WHAT
