### ISSUE TITLE
Handle project upload errors

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#3723]
When we catch errors after attempting to store project or asset data, we should let the user know and attempt to recover if possible.

Scratch 2.0 retries, backing off exponentially if it fails to save. Scratch 2.0 also assumes that the user is logged out when it fails to save sometimes. We should avoid this behavior in 3.0.

This has a few forms:
- [ ] Network timeouts (#3762)
- [ ] The server is returning errors (#3764)
- [ ] User has become logged out (#3764)

But in all cases, we want to prompt the user to download their project ASAP:
- [ ] Modal with project download button (#3761)
