### ISSUE TITLE
Alerts phase 3: appearance

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3842]
(See previous phase: https://github.com/LLK/scratch-gui/issues/3727 )

- [ ] alerts code revisions to improve maintainability https://github.com/LLK/scratch-gui/issues/3840
- [ ] make alerts appear correctly in RTL https://github.com/LLK/scratch-gui/issues/3753
- [ ] cloud variable alerts https://github.com/LLK/scratch-gui/issues/3598
- [ ] alert text for creating vs remixing vs saving as a copy https://github.com/LLK/scratch-gui/issues/3545
- [x] better padding, margin in device connection modal https://github.com/LLK/scratch-gui/pull/3830
