### ISSUE TITLE
Alerts phase 4: complex interactions

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3843]
- [ ] handle network timeout around creating projects https://github.com/LLK/scratch-gui/issues/3723 (has several parts)
- [ ] add error icon https://github.com/LLK/scratch-gui/issues/3822
- [ ] handle complexity around alerts, hardware modals interacting https://github.com/LLK/scratch-gui/issues/3699
- [ ] revisit alerts on project page and fullscreen modes: https://github.com/LLK/scratch-gui/issues/3837
